// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

type AuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthRepository) EXPECT() *AuthRepository_Expecter {
	return &AuthRepository_Expecter{mock: &_m.Mock}
}

// RevokeAllUserTokens provides a mock function for the type AuthRepository
func (_mock *AuthRepository) RevokeAllUserTokens(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_RevokeAllUserTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserTokens'
type AuthRepository_RevokeAllUserTokens_Call struct {
	*mock.Call
}

// RevokeAllUserTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *AuthRepository_Expecter) RevokeAllUserTokens(ctx interface{}, userID interface{}) *AuthRepository_RevokeAllUserTokens_Call {
	return &AuthRepository_RevokeAllUserTokens_Call{Call: _e.mock.On("RevokeAllUserTokens", ctx, userID)}
}

func (_c *AuthRepository_RevokeAllUserTokens_Call) Run(run func(ctx context.Context, userID string)) *AuthRepository_RevokeAllUserTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_RevokeAllUserTokens_Call) Return(err error) *AuthRepository_RevokeAllUserTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_RevokeAllUserTokens_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *AuthRepository_RevokeAllUserTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type AuthRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *AuthRepository_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}) *AuthRepository_RevokeRefreshToken_Call {
	return &AuthRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash)}
}

func (_c *AuthRepository_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *AuthRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_RevokeRefreshToken_Call) Return(err error) *AuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_RevokeRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) error) *AuthRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// StoreRefreshToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) StoreRefreshToken(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, userID, tokenHash, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for StoreRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, tokenHash, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthRepository_StoreRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreRefreshToken'
type AuthRepository_StoreRefreshToken_Call struct {
	*mock.Call
}

// StoreRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tokenHash string
//   - expiresAt time.Time
func (_e *AuthRepository_Expecter) StoreRefreshToken(ctx interface{}, userID interface{}, tokenHash interface{}, expiresAt interface{}) *AuthRepository_StoreRefreshToken_Call {
	return &AuthRepository_StoreRefreshToken_Call{Call: _e.mock.On("StoreRefreshToken", ctx, userID, tokenHash, expiresAt)}
}

func (_c *AuthRepository_StoreRefreshToken_Call) Run(run func(ctx context.Context, userID string, tokenHash string, expiresAt time.Time)) *AuthRepository_StoreRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthRepository_StoreRefreshToken_Call) Return(err error) *AuthRepository_StoreRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthRepository_StoreRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID string, tokenHash string, expiresAt time.Time) error) *AuthRepository_StoreRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type AuthRepository
func (_mock *AuthRepository) ValidateRefreshToken(ctx context.Context, tokenHash string) (string, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthRepository_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type AuthRepository_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *AuthRepository_Expecter) ValidateRefreshToken(ctx interface{}, tokenHash interface{}) *AuthRepository_ValidateRefreshToken_Call {
	return &AuthRepository_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", ctx, tokenHash)}
}

func (_c *AuthRepository_ValidateRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *AuthRepository_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthRepository_ValidateRefreshToken_Call) Return(s string, err error) *AuthRepository_ValidateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthRepository_ValidateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (string, error)) *AuthRepository_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
