syntax = "proto3";

package common.v1;

option go_package = "github.com/beabys/wms/proto/gen/go/common/v1;commonv1";

message Money {
  string amount = 1;
  string currency = 2;
}

message Address {
  string line1 = 1;
  string line2 = 2;
  string city = 3;
  string postal_code = 4;
  string country = 5;
}

message Pagination {
  int32 page = 1;
  int32 limit = 2;
  int32 total = 3;
}

message DateRange {
  string start = 1;
  string end = 2;
}

message ErrorDetail {
  string code = 1;
  string message = 2;
}
