// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Error   *string                 `json:"error,omitempty"`
	Success *bool                   `json:"success,omitempty"`
}

// InboundItemInput defines model for InboundItemInput.
type InboundItemInput struct {
	Dimensions       *string  `json:"dimensions,omitempty"`
	QuantityDeclared int      `json:"quantity_declared"`
	QuantityReceived *int     `json:"quantity_received,omitempty"`
	SKU              string   `json:"sku"`
	Weight           *float64 `json:"weight,omitempty"`
}

// SubmitInboundJSONBody defines parameters for SubmitInbound.
type SubmitInboundJSONBody struct {
	CustomerId   string             `json:"customer_id"`
	ExpectedDate openapi_types.Date `json:"expected_date"`
	Items        []InboundItemInput `json:"items"`
	Notes        *string            `json:"notes,omitempty"`
}

// GetCustomerInboundsParams defines parameters for GetCustomerInbounds.
type GetCustomerInboundsParams struct {
	PageSize  *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetInboundQueueParams defines parameters for GetInboundQueue.
type GetInboundQueueParams struct {
	PageSize  *int    `form:"page_size,omitempty" json:"page_size,omitempty"`
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
	Status    *string `form:"status,omitempty" json:"status,omitempty"`
}

// FlagInboundJSONBody defines parameters for FlagInbound.
type FlagInboundJSONBody struct {
	Reason string `json:"reason"`
}

// HoldInboundJSONBody defines parameters for HoldInbound.
type HoldInboundJSONBody struct {
	Reason string `json:"reason"`
}

// InspectInboundJSONBody defines parameters for InspectInbound.
type InspectInboundJSONBody struct {
	InspectorId string  `json:"inspector_id"`
	Notes       *string `json:"notes,omitempty"`
	Passed      *bool   `json:"passed,omitempty"`
}

// SubmitInboundJSONRequestBody defines body for SubmitInbound for application/json ContentType.
type SubmitInboundJSONRequestBody SubmitInboundJSONBody

// FlagInboundJSONRequestBody defines body for FlagInbound for application/json ContentType.
type FlagInboundJSONRequestBody FlagInboundJSONBody

// HoldInboundJSONRequestBody defines body for HoldInbound for application/json ContentType.
type HoldInboundJSONRequestBody HoldInboundJSONBody

// InspectInboundJSONRequestBody defines body for InspectInbound for application/json ContentType.
type InspectInboundJSONRequestBody InspectInboundJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SubmitInboundWithBody request with any body
	SubmitInboundWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubmitInbound(ctx context.Context, body SubmitInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCustomerInbounds request
	GetCustomerInbounds(ctx context.Context, id string, params *GetCustomerInboundsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInboundQueue request
	GetInboundQueue(ctx context.Context, params *GetInboundQueueParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInbound request
	GetInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ApproveInbound request
	ApproveInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FlagInboundWithBody request with any body
	FlagInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	FlagInbound(ctx context.Context, id string, body FlagInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HoldInboundWithBody request with any body
	HoldInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HoldInbound(ctx context.Context, id string, body HoldInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// InspectInboundWithBody request with any body
	InspectInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	InspectInbound(ctx context.Context, id string, body InspectInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReleaseInbound request
	ReleaseInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SubmitInboundWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitInboundRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubmitInbound(ctx context.Context, body SubmitInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubmitInboundRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCustomerInbounds(ctx context.Context, id string, params *GetCustomerInboundsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomerInboundsRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInboundQueue(ctx context.Context, params *GetInboundQueueParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInboundQueueRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInboundRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ApproveInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewApproveInboundRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FlagInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFlagInboundRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FlagInbound(ctx context.Context, id string, body FlagInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFlagInboundRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HoldInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHoldInboundRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HoldInbound(ctx context.Context, id string, body HoldInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHoldInboundRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InspectInboundWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInspectInboundRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) InspectInbound(ctx context.Context, id string, body InspectInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewInspectInboundRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReleaseInbound(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReleaseInboundRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSubmitInboundRequest calls the generic SubmitInbound builder with application/json body
func NewSubmitInboundRequest(server string, body SubmitInboundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubmitInboundRequestWithBody(server, "application/json", bodyReader)
}

// NewSubmitInboundRequestWithBody generates requests for SubmitInbound with any type of body
func NewSubmitInboundRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCustomerInboundsRequest generates requests for GetCustomerInbounds
func NewGetCustomerInboundsRequest(server string, id string, params *GetCustomerInboundsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/customer/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInboundQueueRequest generates requests for GetInboundQueue
func NewGetInboundQueueRequest(server string, params *GetInboundQueueParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/queue")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_size", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetInboundRequest generates requests for GetInbound
func NewGetInboundRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewApproveInboundRequest generates requests for ApproveInbound
func NewApproveInboundRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s/approve", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFlagInboundRequest calls the generic FlagInbound builder with application/json body
func NewFlagInboundRequest(server string, id string, body FlagInboundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewFlagInboundRequestWithBody(server, id, "application/json", bodyReader)
}

// NewFlagInboundRequestWithBody generates requests for FlagInbound with any type of body
func NewFlagInboundRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s/flag", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHoldInboundRequest calls the generic HoldInbound builder with application/json body
func NewHoldInboundRequest(server string, id string, body HoldInboundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHoldInboundRequestWithBody(server, id, "application/json", bodyReader)
}

// NewHoldInboundRequestWithBody generates requests for HoldInbound with any type of body
func NewHoldInboundRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s/hold", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewInspectInboundRequest calls the generic InspectInbound builder with application/json body
func NewInspectInboundRequest(server string, id string, body InspectInboundJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewInspectInboundRequestWithBody(server, id, "application/json", bodyReader)
}

// NewInspectInboundRequestWithBody generates requests for InspectInbound with any type of body
func NewInspectInboundRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s/inspect", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReleaseInboundRequest generates requests for ReleaseInbound
func NewReleaseInboundRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/inbounds/%s/release", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SubmitInboundWithBodyWithResponse request with any body
	SubmitInboundWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitInboundResponse, error)

	SubmitInboundWithResponse(ctx context.Context, body SubmitInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitInboundResponse, error)

	// GetCustomerInboundsWithResponse request
	GetCustomerInboundsWithResponse(ctx context.Context, id string, params *GetCustomerInboundsParams, reqEditors ...RequestEditorFn) (*GetCustomerInboundsResponse, error)

	// GetInboundQueueWithResponse request
	GetInboundQueueWithResponse(ctx context.Context, params *GetInboundQueueParams, reqEditors ...RequestEditorFn) (*GetInboundQueueResponse, error)

	// GetInboundWithResponse request
	GetInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetInboundResponse, error)

	// ApproveInboundWithResponse request
	ApproveInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ApproveInboundResponse, error)

	// FlagInboundWithBodyWithResponse request with any body
	FlagInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FlagInboundResponse, error)

	FlagInboundWithResponse(ctx context.Context, id string, body FlagInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*FlagInboundResponse, error)

	// HoldInboundWithBodyWithResponse request with any body
	HoldInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HoldInboundResponse, error)

	HoldInboundWithResponse(ctx context.Context, id string, body HoldInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*HoldInboundResponse, error)

	// InspectInboundWithBodyWithResponse request with any body
	InspectInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InspectInboundResponse, error)

	InspectInboundWithResponse(ctx context.Context, id string, body InspectInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*InspectInboundResponse, error)

	// ReleaseInboundWithResponse request
	ReleaseInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ReleaseInboundResponse, error)
}

type SubmitInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r SubmitInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubmitInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SubmitInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetCustomerInboundsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r GetCustomerInboundsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomerInboundsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetCustomerInboundsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetInboundQueueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r GetInboundQueueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInboundQueueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetInboundQueueResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r GetInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ApproveInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r ApproveInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ApproveInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ApproveInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type FlagInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r FlagInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FlagInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r FlagInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HoldInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r HoldInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HoldInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HoldInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type InspectInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r InspectInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r InspectInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r InspectInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReleaseInboundResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ApiResponse
}

// Status returns HTTPResponse.Status
func (r ReleaseInboundResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReleaseInboundResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReleaseInboundResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SubmitInboundWithBodyWithResponse request with arbitrary body returning *SubmitInboundResponse
func (c *ClientWithResponses) SubmitInboundWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubmitInboundResponse, error) {
	rsp, err := c.SubmitInboundWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitInboundResponse(rsp)
}

func (c *ClientWithResponses) SubmitInboundWithResponse(ctx context.Context, body SubmitInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*SubmitInboundResponse, error) {
	rsp, err := c.SubmitInbound(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubmitInboundResponse(rsp)
}

// GetCustomerInboundsWithResponse request returning *GetCustomerInboundsResponse
func (c *ClientWithResponses) GetCustomerInboundsWithResponse(ctx context.Context, id string, params *GetCustomerInboundsParams, reqEditors ...RequestEditorFn) (*GetCustomerInboundsResponse, error) {
	rsp, err := c.GetCustomerInbounds(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomerInboundsResponse(rsp)
}

// GetInboundQueueWithResponse request returning *GetInboundQueueResponse
func (c *ClientWithResponses) GetInboundQueueWithResponse(ctx context.Context, params *GetInboundQueueParams, reqEditors ...RequestEditorFn) (*GetInboundQueueResponse, error) {
	rsp, err := c.GetInboundQueue(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInboundQueueResponse(rsp)
}

// GetInboundWithResponse request returning *GetInboundResponse
func (c *ClientWithResponses) GetInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetInboundResponse, error) {
	rsp, err := c.GetInbound(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInboundResponse(rsp)
}

// ApproveInboundWithResponse request returning *ApproveInboundResponse
func (c *ClientWithResponses) ApproveInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ApproveInboundResponse, error) {
	rsp, err := c.ApproveInbound(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseApproveInboundResponse(rsp)
}

// FlagInboundWithBodyWithResponse request with arbitrary body returning *FlagInboundResponse
func (c *ClientWithResponses) FlagInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*FlagInboundResponse, error) {
	rsp, err := c.FlagInboundWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFlagInboundResponse(rsp)
}

func (c *ClientWithResponses) FlagInboundWithResponse(ctx context.Context, id string, body FlagInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*FlagInboundResponse, error) {
	rsp, err := c.FlagInbound(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFlagInboundResponse(rsp)
}

// HoldInboundWithBodyWithResponse request with arbitrary body returning *HoldInboundResponse
func (c *ClientWithResponses) HoldInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HoldInboundResponse, error) {
	rsp, err := c.HoldInboundWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHoldInboundResponse(rsp)
}

func (c *ClientWithResponses) HoldInboundWithResponse(ctx context.Context, id string, body HoldInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*HoldInboundResponse, error) {
	rsp, err := c.HoldInbound(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHoldInboundResponse(rsp)
}

// InspectInboundWithBodyWithResponse request with arbitrary body returning *InspectInboundResponse
func (c *ClientWithResponses) InspectInboundWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*InspectInboundResponse, error) {
	rsp, err := c.InspectInboundWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInspectInboundResponse(rsp)
}

func (c *ClientWithResponses) InspectInboundWithResponse(ctx context.Context, id string, body InspectInboundJSONRequestBody, reqEditors ...RequestEditorFn) (*InspectInboundResponse, error) {
	rsp, err := c.InspectInbound(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseInspectInboundResponse(rsp)
}

// ReleaseInboundWithResponse request returning *ReleaseInboundResponse
func (c *ClientWithResponses) ReleaseInboundWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*ReleaseInboundResponse, error) {
	rsp, err := c.ReleaseInbound(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReleaseInboundResponse(rsp)
}

// ParseSubmitInboundResponse parses an HTTP response from a SubmitInboundWithResponse call
func ParseSubmitInboundResponse(rsp *http.Response) (*SubmitInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubmitInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetCustomerInboundsResponse parses an HTTP response from a GetCustomerInboundsWithResponse call
func ParseGetCustomerInboundsResponse(rsp *http.Response) (*GetCustomerInboundsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomerInboundsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetInboundQueueResponse parses an HTTP response from a GetInboundQueueWithResponse call
func ParseGetInboundQueueResponse(rsp *http.Response) (*GetInboundQueueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInboundQueueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetInboundResponse parses an HTTP response from a GetInboundWithResponse call
func ParseGetInboundResponse(rsp *http.Response) (*GetInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseApproveInboundResponse parses an HTTP response from a ApproveInboundWithResponse call
func ParseApproveInboundResponse(rsp *http.Response) (*ApproveInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ApproveInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseFlagInboundResponse parses an HTTP response from a FlagInboundWithResponse call
func ParseFlagInboundResponse(rsp *http.Response) (*FlagInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FlagInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHoldInboundResponse parses an HTTP response from a HoldInboundWithResponse call
func ParseHoldInboundResponse(rsp *http.Response) (*HoldInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HoldInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseInspectInboundResponse parses an HTTP response from a InspectInboundWithResponse call
func ParseInspectInboundResponse(rsp *http.Response) (*InspectInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &InspectInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseReleaseInboundResponse parses an HTTP response from a ReleaseInboundWithResponse call
func ParseReleaseInboundResponse(rsp *http.Response) (*ReleaseInboundResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReleaseInboundResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ApiResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit new inbound (customer)
	// (POST /v1/inbounds)
	SubmitInbound(w http.ResponseWriter, r *http.Request)
	// Get customer's inbounds
	// (GET /v1/inbounds/customer/{id})
	GetCustomerInbounds(w http.ResponseWriter, r *http.Request, id string, params GetCustomerInboundsParams)
	// Get ops inbound queue (sorted by expected_date)
	// (GET /v1/inbounds/queue)
	GetInboundQueue(w http.ResponseWriter, r *http.Request, params GetInboundQueueParams)
	// Get inbound detail with items, inspection, hold
	// (GET /v1/inbounds/{id})
	GetInbound(w http.ResponseWriter, r *http.Request, id string)
	// Approve inbound (ops)
	// (POST /v1/inbounds/{id}/approve)
	ApproveInbound(w http.ResponseWriter, r *http.Request, id string)
	// Flag issue with inbound (ops)
	// (POST /v1/inbounds/{id}/flag)
	FlagInbound(w http.ResponseWriter, r *http.Request, id string)
	// Place inbound on hold (ops)
	// (POST /v1/inbounds/{id}/hold)
	HoldInbound(w http.ResponseWriter, r *http.Request, id string)
	// Submit inspection (ops)
	// (POST /v1/inbounds/{id}/inspect)
	InspectInbound(w http.ResponseWriter, r *http.Request, id string)
	// Release inbound from hold (ops)
	// (POST /v1/inbounds/{id}/release)
	ReleaseInbound(w http.ResponseWriter, r *http.Request, id string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Submit new inbound (customer)
// (POST /v1/inbounds)
func (_ Unimplemented) SubmitInbound(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get customer's inbounds
// (GET /v1/inbounds/customer/{id})
func (_ Unimplemented) GetCustomerInbounds(w http.ResponseWriter, r *http.Request, id string, params GetCustomerInboundsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get ops inbound queue (sorted by expected_date)
// (GET /v1/inbounds/queue)
func (_ Unimplemented) GetInboundQueue(w http.ResponseWriter, r *http.Request, params GetInboundQueueParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get inbound detail with items, inspection, hold
// (GET /v1/inbounds/{id})
func (_ Unimplemented) GetInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Approve inbound (ops)
// (POST /v1/inbounds/{id}/approve)
func (_ Unimplemented) ApproveInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Flag issue with inbound (ops)
// (POST /v1/inbounds/{id}/flag)
func (_ Unimplemented) FlagInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place inbound on hold (ops)
// (POST /v1/inbounds/{id}/hold)
func (_ Unimplemented) HoldInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Submit inspection (ops)
// (POST /v1/inbounds/{id}/inspect)
func (_ Unimplemented) InspectInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Release inbound from hold (ops)
// (POST /v1/inbounds/{id}/release)
func (_ Unimplemented) ReleaseInbound(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitInbound operation middleware
func (siw *ServerInterfaceWrapper) SubmitInbound(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitInbound(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCustomerInbounds operation middleware
func (siw *ServerInterfaceWrapper) GetCustomerInbounds(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCustomerInboundsParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCustomerInbounds(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInboundQueue operation middleware
func (siw *ServerInterfaceWrapper) GetInboundQueue(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetInboundQueueParams

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_size", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_size"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_size", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page_token" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page_token", r.URL.Query(), &params.PageToken, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page_token"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page_token", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInboundQueue(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInbound operation middleware
func (siw *ServerInterfaceWrapper) GetInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveInbound operation middleware
func (siw *ServerInterfaceWrapper) ApproveInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FlagInbound operation middleware
func (siw *ServerInterfaceWrapper) FlagInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FlagInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HoldInbound operation middleware
func (siw *ServerInterfaceWrapper) HoldInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HoldInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InspectInbound operation middleware
func (siw *ServerInterfaceWrapper) InspectInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InspectInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReleaseInbound operation middleware
func (siw *ServerInterfaceWrapper) ReleaseInbound(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReleaseInbound(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds", wrapper.SubmitInbound)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/inbounds/customer/{id}", wrapper.GetCustomerInbounds)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/inbounds/queue", wrapper.GetInboundQueue)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/inbounds/{id}", wrapper.GetInbound)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds/{id}/approve", wrapper.ApproveInbound)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds/{id}/flag", wrapper.FlagInbound)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds/{id}/hold", wrapper.HoldInbound)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds/{id}/inspect", wrapper.InspectInbound)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/inbounds/{id}/release", wrapper.ReleaseInbound)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FdNbxs3EP0rBFugKbDxKvUl2JtdwKmAHtL0WBgGRY4kxrscmhzKVQ3994Lcb2tXsYsUToKc7NW+meG8",
	"94ZcPnCJlUUDhjwvHriXW6hE+vfC6g/gLRoP8dE6tOBIQ3qpBIn414SyFKsSeEEuQMZpb4EXHFcfQRI/",
	"ZBycQ3cC6clps4lIH6QEn7I371aIJQjDD4eJxEuzwmDUkqBaGhtoYo26AuM1mmHOvt5dEIY07W8UyFI4",
	"UAOUNgQbcCOYAwl6Nwfzt2Gyyj3ozZYGr0yoVjHkkHEHd0Gnwn+l+Kk1XR+1HiO1WWNqEbx02pJGwwt+",
	"KeQtGPV6je712qEhMIpdvF+yNTqma75YZEhQYiXjpCkq0pLJLq+uYgDP+A6cr7O+OVucLWIraMEIq3nB",
	"z88WZ+c841bQNpGb797kTYH0bNGnnrtiS8UL/mdYVZqaWrzuHzxdotpHsEwrTnHC2lLLFJl/9HEZrTWP",
	"ZZbBE1bgbrSaVAD+tiAJ1I0SlJy8RlcJ4gVPP0w4URNUKXX3z48O1rzgP+T9tOTNqORHRuzdKpwT+/hs",
	"kGDKhY9MMGzl8cLbZU0bos8Spyv9UI9uqvrLYvEsgk+1O9wWUumxB1snSQeCQKUWfagq4fadA5iB+86P",
	"r9qmf45SiI2PRCxbL13H+KG78haeP2h1iIvdwITV3gH92gC7XNGvTlRA4GKRB67jgqOHecaNqNJEt77s",
	"ycwGxBzJ1yS5C+D2fRYrNnDj9T9RtaPgbtM4GU14C4afqn39ciK31P7kWTf1Y6HfATE5gXqSxHcBApyS",
	"ton9I+GmZX0JRWaiPQkK/kvVsibxWD20nWwsCcJeeXQEiq32bLQ1PXFwPzWv/bnw2cf0+uX3QwUkdDnB",
	"sx4B2L2mLUs7fca08ZFmjSZjWyzV03nOhbUOdzB/Fl/UgG+b9IaFx6dQ03t/BKH1zzBxvi7FZp7Zq1Js",
	"/m9aP8d3kwPRIE5/lDS4r+S7I2qzOVI8asK09wGaAfuPyqcpnFX+NyzVd+VfSnk09SY5Vv59KWQ/6Q3m",
	"2bo3O/G89Msa8DWo3/SCsxemuctKbMr70QV4eEMfOmdU44v3T3vKMgcSnZq7tfTH8bP946AE4U8cxx9q",
	"wLd9HDcsPKa36b0b0rXD6tNjGlOA27UEjSv+jlKUTMEOSrRV7C/jwZW84FsiW+R5GQFb9FS8Xbw954fr",
	"w78BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
