// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Data struct {
		Error string `json:"error"`
	} `json:"data"`
	Success bool `json:"success"`
}

// Success defines model for Success.
type Success struct {
	Data    map[string]interface{} `json:"data"`
	Success bool                   `json:"success"`
}

// User defines model for User.
type User struct {
	CreatedAt  *string `json:"created_at,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	Email      *string `json:"email,omitempty"`
	Id         *string `json:"id,omitempty"`
	Role       *string `json:"role,omitempty"`
}

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// Postv1AuthLoginJSONBody defines parameters for Postv1AuthLogin.
type Postv1AuthLoginJSONBody struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Postv1AuthLogoutJSONBody defines parameters for Postv1AuthLogout.
type Postv1AuthLogoutJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// Postv1AuthRefreshJSONBody defines parameters for Postv1AuthRefresh.
type Postv1AuthRefreshJSONBody struct {
	RefreshToken string `json:"refresh_token"`
}

// Postv1AuthRegisterJSONBody defines parameters for Postv1AuthRegister.
type Postv1AuthRegisterJSONBody struct {
	CompanyName *string             `json:"company_name,omitempty"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// Postv1AuthLoginJSONRequestBody defines body for Postv1AuthLogin for application/json ContentType.
type Postv1AuthLoginJSONRequestBody Postv1AuthLoginJSONBody

// Postv1AuthLogoutJSONRequestBody defines body for Postv1AuthLogout for application/json ContentType.
type Postv1AuthLogoutJSONRequestBody Postv1AuthLogoutJSONBody

// Postv1AuthRefreshJSONRequestBody defines body for Postv1AuthRefresh for application/json ContentType.
type Postv1AuthRefreshJSONRequestBody Postv1AuthRefreshJSONBody

// Postv1AuthRegisterJSONRequestBody defines body for Postv1AuthRegister for application/json ContentType.
type Postv1AuthRegisterJSONRequestBody Postv1AuthRegisterJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// Postv1AuthLoginWithBody request with any body
	Postv1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Postv1AuthLogin(ctx context.Context, body Postv1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Postv1AuthLogoutWithBody request with any body
	Postv1AuthLogoutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Postv1AuthLogout(ctx context.Context, body Postv1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Getv1AuthMe request
	Getv1AuthMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Postv1AuthRefreshWithBody request with any body
	Postv1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Postv1AuthRefresh(ctx context.Context, body Postv1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// Postv1AuthRegisterWithBody request with any body
	Postv1AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	Postv1AuthRegister(ctx context.Context, body Postv1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) Postv1AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthLogin(ctx context.Context, body Postv1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthLogoutWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthLogoutRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthLogout(ctx context.Context, body Postv1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthLogoutRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Getv1AuthMe(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetv1AuthMeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthRefreshRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthRefresh(ctx context.Context, body Postv1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthRefreshRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthRegisterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) Postv1AuthRegister(ctx context.Context, body Postv1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostv1AuthRegisterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostv1AuthLoginRequest calls the generic Postv1AuthLogin builder with application/json body
func NewPostv1AuthLoginRequest(server string, body Postv1AuthLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostv1AuthLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewPostv1AuthLoginRequestWithBody generates requests for Postv1AuthLogin with any type of body
func NewPostv1AuthLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostv1AuthLogoutRequest calls the generic Postv1AuthLogout builder with application/json body
func NewPostv1AuthLogoutRequest(server string, body Postv1AuthLogoutJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostv1AuthLogoutRequestWithBody(server, "application/json", bodyReader)
}

// NewPostv1AuthLogoutRequestWithBody generates requests for Postv1AuthLogout with any type of body
func NewPostv1AuthLogoutRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/logout")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetv1AuthMeRequest generates requests for Getv1AuthMe
func NewGetv1AuthMeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostv1AuthRefreshRequest calls the generic Postv1AuthRefresh builder with application/json body
func NewPostv1AuthRefreshRequest(server string, body Postv1AuthRefreshJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostv1AuthRefreshRequestWithBody(server, "application/json", bodyReader)
}

// NewPostv1AuthRefreshRequestWithBody generates requests for Postv1AuthRefresh with any type of body
func NewPostv1AuthRefreshRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/refresh")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostv1AuthRegisterRequest calls the generic Postv1AuthRegister builder with application/json body
func NewPostv1AuthRegisterRequest(server string, body Postv1AuthRegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostv1AuthRegisterRequestWithBody(server, "application/json", bodyReader)
}

// NewPostv1AuthRegisterRequestWithBody generates requests for Postv1AuthRegister with any type of body
func NewPostv1AuthRegisterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/auth/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// Postv1AuthLoginWithBodyWithResponse request with any body
	Postv1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthLoginResponse, error)

	Postv1AuthLoginWithResponse(ctx context.Context, body Postv1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthLoginResponse, error)

	// Postv1AuthLogoutWithBodyWithResponse request with any body
	Postv1AuthLogoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthLogoutResponse, error)

	Postv1AuthLogoutWithResponse(ctx context.Context, body Postv1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthLogoutResponse, error)

	// Getv1AuthMeWithResponse request
	Getv1AuthMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*Getv1AuthMeResponse, error)

	// Postv1AuthRefreshWithBodyWithResponse request with any body
	Postv1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthRefreshResponse, error)

	Postv1AuthRefreshWithResponse(ctx context.Context, body Postv1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthRefreshResponse, error)

	// Postv1AuthRegisterWithBodyWithResponse request with any body
	Postv1AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthRegisterResponse, error)

	Postv1AuthRegisterWithResponse(ctx context.Context, body Postv1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthRegisterResponse, error)
}

type Postv1AuthLoginResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			AccessToken  *string `json:"access_token,omitempty"`
			RefreshToken *string `json:"refresh_token,omitempty"`
			User         *struct {
				CreatedAt  *string `json:"created_at,omitempty"`
				CustomerId *string `json:"customer_id,omitempty"`
				Email      *string `json:"email,omitempty"`
				Id         *string `json:"id,omitempty"`
				Role       *string `json:"role,omitempty"`
			} `json:"user,omitempty"`
		} `json:"data,omitempty"`
		Error   *string `json:"error,omitempty"`
		Success *bool   `json:"success,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r Postv1AuthLoginResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postv1AuthLoginResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r Postv1AuthLoginResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type Postv1AuthLogoutResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Error   *string `json:"error,omitempty"`
		Success *bool   `json:"success,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r Postv1AuthLogoutResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postv1AuthLogoutResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r Postv1AuthLogoutResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type Getv1AuthMeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			User *struct {
				CreatedAt  *string `json:"created_at,omitempty"`
				CustomerId *string `json:"customer_id,omitempty"`
				Email      *string `json:"email,omitempty"`
				Id         *string `json:"id,omitempty"`
				Role       *string `json:"role,omitempty"`
			} `json:"user,omitempty"`
		} `json:"data,omitempty"`
		Error   *string `json:"error,omitempty"`
		Success *bool   `json:"success,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r Getv1AuthMeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Getv1AuthMeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r Getv1AuthMeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type Postv1AuthRefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			AccessToken  *string `json:"access_token,omitempty"`
			RefreshToken *string `json:"refresh_token,omitempty"`
		} `json:"data,omitempty"`
		Error   *string `json:"error,omitempty"`
		Success *bool   `json:"success,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r Postv1AuthRefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postv1AuthRefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r Postv1AuthRefreshResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type Postv1AuthRegisterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			User *User `json:"user,omitempty"`
		} `json:"data,omitempty"`
		Error   *string `json:"error,omitempty"`
		Success *bool   `json:"success,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r Postv1AuthRegisterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r Postv1AuthRegisterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r Postv1AuthRegisterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// Postv1AuthLoginWithBodyWithResponse request with arbitrary body returning *Postv1AuthLoginResponse
func (c *ClientWithResponses) Postv1AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthLoginResponse, error) {
	rsp, err := c.Postv1AuthLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthLoginResponse(rsp)
}

func (c *ClientWithResponses) Postv1AuthLoginWithResponse(ctx context.Context, body Postv1AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthLoginResponse, error) {
	rsp, err := c.Postv1AuthLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthLoginResponse(rsp)
}

// Postv1AuthLogoutWithBodyWithResponse request with arbitrary body returning *Postv1AuthLogoutResponse
func (c *ClientWithResponses) Postv1AuthLogoutWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthLogoutResponse, error) {
	rsp, err := c.Postv1AuthLogoutWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthLogoutResponse(rsp)
}

func (c *ClientWithResponses) Postv1AuthLogoutWithResponse(ctx context.Context, body Postv1AuthLogoutJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthLogoutResponse, error) {
	rsp, err := c.Postv1AuthLogout(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthLogoutResponse(rsp)
}

// Getv1AuthMeWithResponse request returning *Getv1AuthMeResponse
func (c *ClientWithResponses) Getv1AuthMeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*Getv1AuthMeResponse, error) {
	rsp, err := c.Getv1AuthMe(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetv1AuthMeResponse(rsp)
}

// Postv1AuthRefreshWithBodyWithResponse request with arbitrary body returning *Postv1AuthRefreshResponse
func (c *ClientWithResponses) Postv1AuthRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthRefreshResponse, error) {
	rsp, err := c.Postv1AuthRefreshWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthRefreshResponse(rsp)
}

func (c *ClientWithResponses) Postv1AuthRefreshWithResponse(ctx context.Context, body Postv1AuthRefreshJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthRefreshResponse, error) {
	rsp, err := c.Postv1AuthRefresh(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthRefreshResponse(rsp)
}

// Postv1AuthRegisterWithBodyWithResponse request with arbitrary body returning *Postv1AuthRegisterResponse
func (c *ClientWithResponses) Postv1AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*Postv1AuthRegisterResponse, error) {
	rsp, err := c.Postv1AuthRegisterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthRegisterResponse(rsp)
}

func (c *ClientWithResponses) Postv1AuthRegisterWithResponse(ctx context.Context, body Postv1AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*Postv1AuthRegisterResponse, error) {
	rsp, err := c.Postv1AuthRegister(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostv1AuthRegisterResponse(rsp)
}

// ParsePostv1AuthLoginResponse parses an HTTP response from a Postv1AuthLoginWithResponse call
func ParsePostv1AuthLoginResponse(rsp *http.Response) (*Postv1AuthLoginResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postv1AuthLoginResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				AccessToken  *string `json:"access_token,omitempty"`
				RefreshToken *string `json:"refresh_token,omitempty"`
				User         *struct {
					CreatedAt  *string `json:"created_at,omitempty"`
					CustomerId *string `json:"customer_id,omitempty"`
					Email      *string `json:"email,omitempty"`
					Id         *string `json:"id,omitempty"`
					Role       *string `json:"role,omitempty"`
				} `json:"user,omitempty"`
			} `json:"data,omitempty"`
			Error   *string `json:"error,omitempty"`
			Success *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostv1AuthLogoutResponse parses an HTTP response from a Postv1AuthLogoutWithResponse call
func ParsePostv1AuthLogoutResponse(rsp *http.Response) (*Postv1AuthLogoutResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postv1AuthLogoutResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Error   *string `json:"error,omitempty"`
			Success *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetv1AuthMeResponse parses an HTTP response from a Getv1AuthMeWithResponse call
func ParseGetv1AuthMeResponse(rsp *http.Response) (*Getv1AuthMeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Getv1AuthMeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				User *struct {
					CreatedAt  *string `json:"created_at,omitempty"`
					CustomerId *string `json:"customer_id,omitempty"`
					Email      *string `json:"email,omitempty"`
					Id         *string `json:"id,omitempty"`
					Role       *string `json:"role,omitempty"`
				} `json:"user,omitempty"`
			} `json:"data,omitempty"`
			Error   *string `json:"error,omitempty"`
			Success *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostv1AuthRefreshResponse parses an HTTP response from a Postv1AuthRefreshWithResponse call
func ParsePostv1AuthRefreshResponse(rsp *http.Response) (*Postv1AuthRefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postv1AuthRefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				AccessToken  *string `json:"access_token,omitempty"`
				RefreshToken *string `json:"refresh_token,omitempty"`
			} `json:"data,omitempty"`
			Error   *string `json:"error,omitempty"`
			Success *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostv1AuthRegisterResponse parses an HTTP response from a Postv1AuthRegisterWithResponse call
func ParsePostv1AuthRegisterResponse(rsp *http.Response) (*Postv1AuthRegisterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &Postv1AuthRegisterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				User *User `json:"user,omitempty"`
			} `json:"data,omitempty"`
			Error   *string `json:"error,omitempty"`
			Success *bool   `json:"success,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user with email and password
	// (POST /v1/auth/login)
	Postv1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Invalidate the current session
	// (POST /v1/auth/logout)
	Postv1AuthLogout(w http.ResponseWriter, r *http.Request)
	// Get current user profile
	// (GET /v1/auth/me)
	Getv1AuthMe(w http.ResponseWriter, r *http.Request)
	// Refresh access token using refresh token
	// (POST /v1/auth/refresh)
	Postv1AuthRefresh(w http.ResponseWriter, r *http.Request)
	// Register a new user account
	// (POST /v1/auth/register)
	Postv1AuthRegister(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate user with email and password
// (POST /v1/auth/login)
func (_ Unimplemented) Postv1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Invalidate the current session
// (POST /v1/auth/logout)
func (_ Unimplemented) Postv1AuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user profile
// (GET /v1/auth/me)
func (_ Unimplemented) Getv1AuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh access token using refresh token
// (POST /v1/auth/refresh)
func (_ Unimplemented) Postv1AuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user account
// (POST /v1/auth/register)
func (_ Unimplemented) Postv1AuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Postv1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) Postv1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Postv1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Postv1AuthLogout operation middleware
func (siw *ServerInterfaceWrapper) Postv1AuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Postv1AuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Getv1AuthMe operation middleware
func (siw *ServerInterfaceWrapper) Getv1AuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Getv1AuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Postv1AuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) Postv1AuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Postv1AuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Postv1AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) Postv1AuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Postv1AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/login", wrapper.Postv1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/logout", wrapper.Postv1AuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/auth/me", wrapper.Getv1AuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/refresh", wrapper.Postv1AuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/register", wrapper.Postv1AuthRegister)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FdNT9w8EP4r1rzvMbBLe8utKxVE1UpVoe0BoZVJJhtDYqfjMWiF9r9X/siyH1lAKqxU0VvizIxn5nme",
	"cXwPhWk7o1GzhfwebFFjK8PjRyJD/qEj0yGxwrBcSpbbq9gb87xDyMEyKT2DxSIDwl9OEZaQXySzy6w3",
	"M1fXWDAsMrCuKNDalRBXxjQo9VaM3jKLqQwFO3sINpz8627/3eJA4wpCyVhOJQ/0KYPCWTYt0lSVg9+x",
	"laoZ/LLDgUyDw4hsJOzLx8KR4vmZhz+mO0FJSB8c1/7tKrwdG2p9+vDp5zlkkSyhV+ErLCPXzB0sfGCl",
	"KxMaj7Yg1bEyGnKYyOIGdXlQGTqoyGhGXYrKkJCOa9SsCukthW9feLKHPrhiXxH4nMTk+BgyuEWyMeTR",
	"4fhw7Ms2HWrZKcjhfVjKoJNch5JGt0cjv8OoMTOlA0LGBjSWG52WkMNXY/nHkd/mczCMBEDLE1POA5Qh",
	"5eApu65J6Y6urdEPIhoQSQ9h1fcxrmTb4HXS2jtD5TMklUIsPbYZue7C5DAs2M5oGzN7Nx7/QV3DI0EG",
	"nUzZ3KAeJihWhLZ+xML9dULamgW7BuNTI2cAwnUNpRlXuUZEOgcdu7aVNE8iSUpC4fso7hTXIhQvpC7F",
	"ki/eb1UZxvEzpeEtX0obT5Fhg/Xr5vun/KvBGtsq7BLdDVxP9a1sVOlR5RpF4YhQs7BowyBcA7MNtJ3h",
	"AI4nmGD8grCHWfBPyLsR938LoiNTqQbXDmPIL9aP4YvLxeUqF06QlwRwm1GWLEhSeY6mvyXTNyrqVzrH",
	"9sqmc5+ESClhuTJImvnGKEloi1igCOkLZ5We9f5xbZNOM2U5yflJPiXblyKUv6xIPZ9q2eLjM+FN/GL1",
	"Y/V/wgpy+G/0cJkbpZvcKFxG9svBCHtkxO6TrCeHkELjXRxgsiiM0yHo4ncAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
