// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/beabys/wms/proto/gen/go/customer/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewGrpcClient creates a new instance of GrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcClient {
	mock := &GrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GrpcClient is an autogenerated mock type for the GrpcClient type
type GrpcClient struct {
	mock.Mock
}

type GrpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GrpcClient) EXPECT() *GrpcClient_Expecter {
	return &GrpcClient_Expecter{mock: &_m.Mock}
}

// ApproveCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ApproveCustomer(ctx context.Context, id string, approvedBy string) (*customerv1.ApproveCustomerResponse, error) {
	ret := _mock.Called(ctx, id, approvedBy)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCustomer")
	}

	var r0 *customerv1.ApproveCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*customerv1.ApproveCustomerResponse, error)); ok {
		return returnFunc(ctx, id, approvedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *customerv1.ApproveCustomerResponse); ok {
		r0 = returnFunc(ctx, id, approvedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.ApproveCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, approvedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ApproveCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveCustomer'
type GrpcClient_ApproveCustomer_Call struct {
	*mock.Call
}

// ApproveCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - approvedBy string
func (_e *GrpcClient_Expecter) ApproveCustomer(ctx interface{}, id interface{}, approvedBy interface{}) *GrpcClient_ApproveCustomer_Call {
	return &GrpcClient_ApproveCustomer_Call{Call: _e.mock.On("ApproveCustomer", ctx, id, approvedBy)}
}

func (_c *GrpcClient_ApproveCustomer_Call) Run(run func(ctx context.Context, id string, approvedBy string)) *GrpcClient_ApproveCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_ApproveCustomer_Call) Return(approveCustomerResponse *customerv1.ApproveCustomerResponse, err error) *GrpcClient_ApproveCustomer_Call {
	_c.Call.Return(approveCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_ApproveCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, approvedBy string) (*customerv1.ApproveCustomerResponse, error)) *GrpcClient_ApproveCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// AssignCompanyRole provides a mock function for the type GrpcClient
func (_mock *GrpcClient) AssignCompanyRole(ctx context.Context, req *customerv1.AssignCompanyRoleRequest) (*customerv1.AssignCompanyRoleResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignCompanyRole")
	}

	var r0 *customerv1.AssignCompanyRoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.AssignCompanyRoleRequest) (*customerv1.AssignCompanyRoleResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.AssignCompanyRoleRequest) *customerv1.AssignCompanyRoleResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.AssignCompanyRoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.AssignCompanyRoleRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_AssignCompanyRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignCompanyRole'
type GrpcClient_AssignCompanyRole_Call struct {
	*mock.Call
}

// AssignCompanyRole is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.AssignCompanyRoleRequest
func (_e *GrpcClient_Expecter) AssignCompanyRole(ctx interface{}, req interface{}) *GrpcClient_AssignCompanyRole_Call {
	return &GrpcClient_AssignCompanyRole_Call{Call: _e.mock.On("AssignCompanyRole", ctx, req)}
}

func (_c *GrpcClient_AssignCompanyRole_Call) Run(run func(ctx context.Context, req *customerv1.AssignCompanyRoleRequest)) *GrpcClient_AssignCompanyRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.AssignCompanyRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.AssignCompanyRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_AssignCompanyRole_Call) Return(assignCompanyRoleResponse *customerv1.AssignCompanyRoleResponse, err error) *GrpcClient_AssignCompanyRole_Call {
	_c.Call.Return(assignCompanyRoleResponse, err)
	return _c
}

func (_c *GrpcClient_AssignCompanyRole_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.AssignCompanyRoleRequest) (*customerv1.AssignCompanyRoleResponse, error)) *GrpcClient_AssignCompanyRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) GetCustomer(ctx context.Context, id string) (*customerv1.GetCustomerResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomer")
	}

	var r0 *customerv1.GetCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*customerv1.GetCustomerResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *customerv1.GetCustomerResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_GetCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomer'
type GrpcClient_GetCustomer_Call struct {
	*mock.Call
}

// GetCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GrpcClient_Expecter) GetCustomer(ctx interface{}, id interface{}) *GrpcClient_GetCustomer_Call {
	return &GrpcClient_GetCustomer_Call{Call: _e.mock.On("GetCustomer", ctx, id)}
}

func (_c *GrpcClient_GetCustomer_Call) Run(run func(ctx context.Context, id string)) *GrpcClient_GetCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_GetCustomer_Call) Return(getCustomerResponse *customerv1.GetCustomerResponse, err error) *GrpcClient_GetCustomer_Call {
	_c.Call.Return(getCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_GetCustomer_Call) RunAndReturn(run func(ctx context.Context, id string) (*customerv1.GetCustomerResponse, error)) *GrpcClient_GetCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerByAdminID provides a mock function for the type GrpcClient
func (_mock *GrpcClient) GetCustomerByAdminID(ctx context.Context, adminUserID string) (*customerv1.GetCustomerByAdminIDResponse, error) {
	ret := _mock.Called(ctx, adminUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByAdminID")
	}

	var r0 *customerv1.GetCustomerByAdminIDResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*customerv1.GetCustomerByAdminIDResponse, error)); ok {
		return returnFunc(ctx, adminUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *customerv1.GetCustomerByAdminIDResponse); ok {
		r0 = returnFunc(ctx, adminUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetCustomerByAdminIDResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, adminUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_GetCustomerByAdminID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerByAdminID'
type GrpcClient_GetCustomerByAdminID_Call struct {
	*mock.Call
}

// GetCustomerByAdminID is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID string
func (_e *GrpcClient_Expecter) GetCustomerByAdminID(ctx interface{}, adminUserID interface{}) *GrpcClient_GetCustomerByAdminID_Call {
	return &GrpcClient_GetCustomerByAdminID_Call{Call: _e.mock.On("GetCustomerByAdminID", ctx, adminUserID)}
}

func (_c *GrpcClient_GetCustomerByAdminID_Call) Run(run func(ctx context.Context, adminUserID string)) *GrpcClient_GetCustomerByAdminID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_GetCustomerByAdminID_Call) Return(getCustomerByAdminIDResponse *customerv1.GetCustomerByAdminIDResponse, err error) *GrpcClient_GetCustomerByAdminID_Call {
	_c.Call.Return(getCustomerByAdminIDResponse, err)
	return _c
}

func (_c *GrpcClient_GetCustomerByAdminID_Call) RunAndReturn(run func(ctx context.Context, adminUserID string) (*customerv1.GetCustomerByAdminIDResponse, error)) *GrpcClient_GetCustomerByAdminID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissions provides a mock function for the type GrpcClient
func (_mock *GrpcClient) GetUserPermissions(ctx context.Context, req *customerv1.GetUserPermissionsRequest) (*customerv1.GetUserPermissionsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 *customerv1.GetUserPermissionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.GetUserPermissionsRequest) (*customerv1.GetUserPermissionsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.GetUserPermissionsRequest) *customerv1.GetUserPermissionsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.GetUserPermissionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.GetUserPermissionsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type GrpcClient_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.GetUserPermissionsRequest
func (_e *GrpcClient_Expecter) GetUserPermissions(ctx interface{}, req interface{}) *GrpcClient_GetUserPermissions_Call {
	return &GrpcClient_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, req)}
}

func (_c *GrpcClient_GetUserPermissions_Call) Run(run func(ctx context.Context, req *customerv1.GetUserPermissionsRequest)) *GrpcClient_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.GetUserPermissionsRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.GetUserPermissionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_GetUserPermissions_Call) Return(getUserPermissionsResponse *customerv1.GetUserPermissionsResponse, err error) *GrpcClient_GetUserPermissions_Call {
	_c.Call.Return(getUserPermissionsResponse, err)
	return _c
}

func (_c *GrpcClient_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.GetUserPermissionsRequest) (*customerv1.GetUserPermissionsResponse, error)) *GrpcClient_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditLogs provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListAuditLogs(ctx context.Context, req *customerv1.ListAuditLogsRequest) (*customerv1.ListAuditLogsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditLogs")
	}

	var r0 *customerv1.ListAuditLogsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListAuditLogsRequest) (*customerv1.ListAuditLogsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListAuditLogsRequest) *customerv1.ListAuditLogsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.ListAuditLogsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.ListAuditLogsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditLogs'
type GrpcClient_ListAuditLogs_Call struct {
	*mock.Call
}

// ListAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.ListAuditLogsRequest
func (_e *GrpcClient_Expecter) ListAuditLogs(ctx interface{}, req interface{}) *GrpcClient_ListAuditLogs_Call {
	return &GrpcClient_ListAuditLogs_Call{Call: _e.mock.On("ListAuditLogs", ctx, req)}
}

func (_c *GrpcClient_ListAuditLogs_Call) Run(run func(ctx context.Context, req *customerv1.ListAuditLogsRequest)) *GrpcClient_ListAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.ListAuditLogsRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.ListAuditLogsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListAuditLogs_Call) Return(listAuditLogsResponse *customerv1.ListAuditLogsResponse, err error) *GrpcClient_ListAuditLogs_Call {
	_c.Call.Return(listAuditLogsResponse, err)
	return _c
}

func (_c *GrpcClient_ListAuditLogs_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.ListAuditLogsRequest) (*customerv1.ListAuditLogsResponse, error)) *GrpcClient_ListAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompanyRoles provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListCompanyRoles(ctx context.Context, req *customerv1.ListCompanyRolesRequest) (*customerv1.ListCompanyRolesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanyRoles")
	}

	var r0 *customerv1.ListCompanyRolesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListCompanyRolesRequest) (*customerv1.ListCompanyRolesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListCompanyRolesRequest) *customerv1.ListCompanyRolesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.ListCompanyRolesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.ListCompanyRolesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListCompanyRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanyRoles'
type GrpcClient_ListCompanyRoles_Call struct {
	*mock.Call
}

// ListCompanyRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.ListCompanyRolesRequest
func (_e *GrpcClient_Expecter) ListCompanyRoles(ctx interface{}, req interface{}) *GrpcClient_ListCompanyRoles_Call {
	return &GrpcClient_ListCompanyRoles_Call{Call: _e.mock.On("ListCompanyRoles", ctx, req)}
}

func (_c *GrpcClient_ListCompanyRoles_Call) Run(run func(ctx context.Context, req *customerv1.ListCompanyRolesRequest)) *GrpcClient_ListCompanyRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.ListCompanyRolesRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.ListCompanyRolesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListCompanyRoles_Call) Return(listCompanyRolesResponse *customerv1.ListCompanyRolesResponse, err error) *GrpcClient_ListCompanyRoles_Call {
	_c.Call.Return(listCompanyRolesResponse, err)
	return _c
}

func (_c *GrpcClient_ListCompanyRoles_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.ListCompanyRolesRequest) (*customerv1.ListCompanyRolesResponse, error)) *GrpcClient_ListCompanyRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListCustomers provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListCustomers(ctx context.Context, req *customerv1.ListCustomersRequest) (*customerv1.ListCustomersResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomers")
	}

	var r0 *customerv1.ListCustomersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListCustomersRequest) (*customerv1.ListCustomersResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.ListCustomersRequest) *customerv1.ListCustomersResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.ListCustomersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.ListCustomersRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCustomers'
type GrpcClient_ListCustomers_Call struct {
	*mock.Call
}

// ListCustomers is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.ListCustomersRequest
func (_e *GrpcClient_Expecter) ListCustomers(ctx interface{}, req interface{}) *GrpcClient_ListCustomers_Call {
	return &GrpcClient_ListCustomers_Call{Call: _e.mock.On("ListCustomers", ctx, req)}
}

func (_c *GrpcClient_ListCustomers_Call) Run(run func(ctx context.Context, req *customerv1.ListCustomersRequest)) *GrpcClient_ListCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.ListCustomersRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.ListCustomersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListCustomers_Call) Return(listCustomersResponse *customerv1.ListCustomersResponse, err error) *GrpcClient_ListCustomers_Call {
	_c.Call.Return(listCustomersResponse, err)
	return _c
}

func (_c *GrpcClient_ListCustomers_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.ListCustomersRequest) (*customerv1.ListCustomersResponse, error)) *GrpcClient_ListCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) RegisterCustomer(ctx context.Context, req *customerv1.RegisterCustomerRequest) (*customerv1.RegisterCustomerResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCustomer")
	}

	var r0 *customerv1.RegisterCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.RegisterCustomerRequest) (*customerv1.RegisterCustomerResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.RegisterCustomerRequest) *customerv1.RegisterCustomerResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.RegisterCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.RegisterCustomerRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_RegisterCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCustomer'
type GrpcClient_RegisterCustomer_Call struct {
	*mock.Call
}

// RegisterCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.RegisterCustomerRequest
func (_e *GrpcClient_Expecter) RegisterCustomer(ctx interface{}, req interface{}) *GrpcClient_RegisterCustomer_Call {
	return &GrpcClient_RegisterCustomer_Call{Call: _e.mock.On("RegisterCustomer", ctx, req)}
}

func (_c *GrpcClient_RegisterCustomer_Call) Run(run func(ctx context.Context, req *customerv1.RegisterCustomerRequest)) *GrpcClient_RegisterCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.RegisterCustomerRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.RegisterCustomerRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_RegisterCustomer_Call) Return(registerCustomerResponse *customerv1.RegisterCustomerResponse, err error) *GrpcClient_RegisterCustomer_Call {
	_c.Call.Return(registerCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_RegisterCustomer_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.RegisterCustomerRequest) (*customerv1.RegisterCustomerResponse, error)) *GrpcClient_RegisterCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// RejectCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) RejectCustomer(ctx context.Context, id string, reason string) (*customerv1.RejectCustomerResponse, error) {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for RejectCustomer")
	}

	var r0 *customerv1.RejectCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*customerv1.RejectCustomerResponse, error)); ok {
		return returnFunc(ctx, id, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *customerv1.RejectCustomerResponse); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.RejectCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_RejectCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectCustomer'
type GrpcClient_RejectCustomer_Call struct {
	*mock.Call
}

// RejectCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reason string
func (_e *GrpcClient_Expecter) RejectCustomer(ctx interface{}, id interface{}, reason interface{}) *GrpcClient_RejectCustomer_Call {
	return &GrpcClient_RejectCustomer_Call{Call: _e.mock.On("RejectCustomer", ctx, id, reason)}
}

func (_c *GrpcClient_RejectCustomer_Call) Run(run func(ctx context.Context, id string, reason string)) *GrpcClient_RejectCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_RejectCustomer_Call) Return(rejectCustomerResponse *customerv1.RejectCustomerResponse, err error) *GrpcClient_RejectCustomer_Call {
	_c.Call.Return(rejectCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_RejectCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, reason string) (*customerv1.RejectCustomerResponse, error)) *GrpcClient_RejectCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) RestoreCustomer(ctx context.Context, id string, restoredBy string) (*customerv1.RestoreCustomerResponse, error) {
	ret := _mock.Called(ctx, id, restoredBy)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCustomer")
	}

	var r0 *customerv1.RestoreCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*customerv1.RestoreCustomerResponse, error)); ok {
		return returnFunc(ctx, id, restoredBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *customerv1.RestoreCustomerResponse); ok {
		r0 = returnFunc(ctx, id, restoredBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.RestoreCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, restoredBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_RestoreCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCustomer'
type GrpcClient_RestoreCustomer_Call struct {
	*mock.Call
}

// RestoreCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - restoredBy string
func (_e *GrpcClient_Expecter) RestoreCustomer(ctx interface{}, id interface{}, restoredBy interface{}) *GrpcClient_RestoreCustomer_Call {
	return &GrpcClient_RestoreCustomer_Call{Call: _e.mock.On("RestoreCustomer", ctx, id, restoredBy)}
}

func (_c *GrpcClient_RestoreCustomer_Call) Run(run func(ctx context.Context, id string, restoredBy string)) *GrpcClient_RestoreCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_RestoreCustomer_Call) Return(restoreCustomerResponse *customerv1.RestoreCustomerResponse, err error) *GrpcClient_RestoreCustomer_Call {
	_c.Call.Return(restoreCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_RestoreCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, restoredBy string) (*customerv1.RestoreCustomerResponse, error)) *GrpcClient_RestoreCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) SuspendCustomer(ctx context.Context, id string, reason string) (*customerv1.SuspendCustomerResponse, error) {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for SuspendCustomer")
	}

	var r0 *customerv1.SuspendCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*customerv1.SuspendCustomerResponse, error)); ok {
		return returnFunc(ctx, id, reason)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *customerv1.SuspendCustomerResponse); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.SuspendCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, reason)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_SuspendCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendCustomer'
type GrpcClient_SuspendCustomer_Call struct {
	*mock.Call
}

// SuspendCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reason string
func (_e *GrpcClient_Expecter) SuspendCustomer(ctx interface{}, id interface{}, reason interface{}) *GrpcClient_SuspendCustomer_Call {
	return &GrpcClient_SuspendCustomer_Call{Call: _e.mock.On("SuspendCustomer", ctx, id, reason)}
}

func (_c *GrpcClient_SuspendCustomer_Call) Run(run func(ctx context.Context, id string, reason string)) *GrpcClient_SuspendCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_SuspendCustomer_Call) Return(suspendCustomerResponse *customerv1.SuspendCustomerResponse, err error) *GrpcClient_SuspendCustomer_Call {
	_c.Call.Return(suspendCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_SuspendCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, reason string) (*customerv1.SuspendCustomerResponse, error)) *GrpcClient_SuspendCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomer provides a mock function for the type GrpcClient
func (_mock *GrpcClient) UpdateCustomer(ctx context.Context, req *customerv1.UpdateCustomerRequest) (*customerv1.UpdateCustomerResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 *customerv1.UpdateCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerRequest) (*customerv1.UpdateCustomerResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *customerv1.UpdateCustomerRequest) *customerv1.UpdateCustomerResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customerv1.UpdateCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *customerv1.UpdateCustomerRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_UpdateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomer'
type GrpcClient_UpdateCustomer_Call struct {
	*mock.Call
}

// UpdateCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *customerv1.UpdateCustomerRequest
func (_e *GrpcClient_Expecter) UpdateCustomer(ctx interface{}, req interface{}) *GrpcClient_UpdateCustomer_Call {
	return &GrpcClient_UpdateCustomer_Call{Call: _e.mock.On("UpdateCustomer", ctx, req)}
}

func (_c *GrpcClient_UpdateCustomer_Call) Run(run func(ctx context.Context, req *customerv1.UpdateCustomerRequest)) *GrpcClient_UpdateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *customerv1.UpdateCustomerRequest
		if args[1] != nil {
			arg1 = args[1].(*customerv1.UpdateCustomerRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_UpdateCustomer_Call) Return(updateCustomerResponse *customerv1.UpdateCustomerResponse, err error) *GrpcClient_UpdateCustomer_Call {
	_c.Call.Return(updateCustomerResponse, err)
	return _c
}

func (_c *GrpcClient_UpdateCustomer_Call) RunAndReturn(run func(ctx context.Context, req *customerv1.UpdateCustomerRequest) (*customerv1.UpdateCustomerResponse, error)) *GrpcClient_UpdateCustomer_Call {
	_c.Call.Return(run)
	return _c
}
