// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpadapter

import (
	"context"

	"github.com/beabys/wms/customer-service-bff/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCustomerHandlerService creates a new instance of CustomerHandlerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerHandlerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerHandlerService {
	mock := &CustomerHandlerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomerHandlerService is an autogenerated mock type for the CustomerHandlerService type
type CustomerHandlerService struct {
	mock.Mock
}

type CustomerHandlerService_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerHandlerService) EXPECT() *CustomerHandlerService_Expecter {
	return &CustomerHandlerService_Expecter{mock: &_m.Mock}
}

// ApproveCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) ApproveCustomer(ctx context.Context, id string, approvedBy string) (*model.CustomerResponse, error) {
	ret := _mock.Called(ctx, id, approvedBy)

	if len(ret) == 0 {
		panic("no return value specified for ApproveCustomer")
	}

	var r0 *model.CustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.CustomerResponse, error)); ok {
		return returnFunc(ctx, id, approvedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.CustomerResponse); ok {
		r0 = returnFunc(ctx, id, approvedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, approvedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_ApproveCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveCustomer'
type CustomerHandlerService_ApproveCustomer_Call struct {
	*mock.Call
}

// ApproveCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - approvedBy string
func (_e *CustomerHandlerService_Expecter) ApproveCustomer(ctx interface{}, id interface{}, approvedBy interface{}) *CustomerHandlerService_ApproveCustomer_Call {
	return &CustomerHandlerService_ApproveCustomer_Call{Call: _e.mock.On("ApproveCustomer", ctx, id, approvedBy)}
}

func (_c *CustomerHandlerService_ApproveCustomer_Call) Run(run func(ctx context.Context, id string, approvedBy string)) *CustomerHandlerService_ApproveCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_ApproveCustomer_Call) Return(customerResponse *model.CustomerResponse, err error) *CustomerHandlerService_ApproveCustomer_Call {
	_c.Call.Return(customerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_ApproveCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, approvedBy string) (*model.CustomerResponse, error)) *CustomerHandlerService_ApproveCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// AssignCompanyRole provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) AssignCompanyRole(ctx context.Context, req *model.AssignCompanyRoleRequest) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for AssignCompanyRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AssignCompanyRoleRequest) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerHandlerService_AssignCompanyRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignCompanyRole'
type CustomerHandlerService_AssignCompanyRole_Call struct {
	*mock.Call
}

// AssignCompanyRole is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.AssignCompanyRoleRequest
func (_e *CustomerHandlerService_Expecter) AssignCompanyRole(ctx interface{}, req interface{}) *CustomerHandlerService_AssignCompanyRole_Call {
	return &CustomerHandlerService_AssignCompanyRole_Call{Call: _e.mock.On("AssignCompanyRole", ctx, req)}
}

func (_c *CustomerHandlerService_AssignCompanyRole_Call) Run(run func(ctx context.Context, req *model.AssignCompanyRoleRequest)) *CustomerHandlerService_AssignCompanyRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AssignCompanyRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*model.AssignCompanyRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_AssignCompanyRole_Call) Return(err error) *CustomerHandlerService_AssignCompanyRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerHandlerService_AssignCompanyRole_Call) RunAndReturn(run func(ctx context.Context, req *model.AssignCompanyRoleRequest) error) *CustomerHandlerService_AssignCompanyRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) GetCustomer(ctx context.Context, id string) (*model.CustomerResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomer")
	}

	var r0 *model.CustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CustomerResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CustomerResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_GetCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomer'
type CustomerHandlerService_GetCustomer_Call struct {
	*mock.Call
}

// GetCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CustomerHandlerService_Expecter) GetCustomer(ctx interface{}, id interface{}) *CustomerHandlerService_GetCustomer_Call {
	return &CustomerHandlerService_GetCustomer_Call{Call: _e.mock.On("GetCustomer", ctx, id)}
}

func (_c *CustomerHandlerService_GetCustomer_Call) Run(run func(ctx context.Context, id string)) *CustomerHandlerService_GetCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_GetCustomer_Call) Return(customerResponse *model.CustomerResponse, err error) *CustomerHandlerService_GetCustomer_Call {
	_c.Call.Return(customerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_GetCustomer_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.CustomerResponse, error)) *CustomerHandlerService_GetCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) GetMyCustomer(ctx context.Context, adminUserID string) (*model.CustomerResponse, error) {
	ret := _mock.Called(ctx, adminUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetMyCustomer")
	}

	var r0 *model.CustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CustomerResponse, error)); ok {
		return returnFunc(ctx, adminUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CustomerResponse); ok {
		r0 = returnFunc(ctx, adminUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, adminUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_GetMyCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyCustomer'
type CustomerHandlerService_GetMyCustomer_Call struct {
	*mock.Call
}

// GetMyCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - adminUserID string
func (_e *CustomerHandlerService_Expecter) GetMyCustomer(ctx interface{}, adminUserID interface{}) *CustomerHandlerService_GetMyCustomer_Call {
	return &CustomerHandlerService_GetMyCustomer_Call{Call: _e.mock.On("GetMyCustomer", ctx, adminUserID)}
}

func (_c *CustomerHandlerService_GetMyCustomer_Call) Run(run func(ctx context.Context, adminUserID string)) *CustomerHandlerService_GetMyCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_GetMyCustomer_Call) Return(customerResponse *model.CustomerResponse, err error) *CustomerHandlerService_GetMyCustomer_Call {
	_c.Call.Return(customerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_GetMyCustomer_Call) RunAndReturn(run func(ctx context.Context, adminUserID string) (*model.CustomerResponse, error)) *CustomerHandlerService_GetMyCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPermissions provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) GetUserPermissions(ctx context.Context, userID string, customerID string) (*model.PermissionsResponse, error) {
	ret := _mock.Called(ctx, userID, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPermissions")
	}

	var r0 *model.PermissionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.PermissionsResponse, error)); ok {
		return returnFunc(ctx, userID, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.PermissionsResponse); ok {
		r0 = returnFunc(ctx, userID, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.PermissionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_GetUserPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPermissions'
type CustomerHandlerService_GetUserPermissions_Call struct {
	*mock.Call
}

// GetUserPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - customerID string
func (_e *CustomerHandlerService_Expecter) GetUserPermissions(ctx interface{}, userID interface{}, customerID interface{}) *CustomerHandlerService_GetUserPermissions_Call {
	return &CustomerHandlerService_GetUserPermissions_Call{Call: _e.mock.On("GetUserPermissions", ctx, userID, customerID)}
}

func (_c *CustomerHandlerService_GetUserPermissions_Call) Run(run func(ctx context.Context, userID string, customerID string)) *CustomerHandlerService_GetUserPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_GetUserPermissions_Call) Return(permissionsResponse *model.PermissionsResponse, err error) *CustomerHandlerService_GetUserPermissions_Call {
	_c.Call.Return(permissionsResponse, err)
	return _c
}

func (_c *CustomerHandlerService_GetUserPermissions_Call) RunAndReturn(run func(ctx context.Context, userID string, customerID string) (*model.PermissionsResponse, error)) *CustomerHandlerService_GetUserPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditLogs provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) ListAuditLogs(ctx context.Context, customerID string, page int, pageSize int) (*model.AuditLogListResponse, error) {
	ret := _mock.Called(ctx, customerID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditLogs")
	}

	var r0 *model.AuditLogListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) (*model.AuditLogListResponse, error)); ok {
		return returnFunc(ctx, customerID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) *model.AuditLogListResponse); ok {
		r0 = returnFunc(ctx, customerID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuditLogListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = returnFunc(ctx, customerID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_ListAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditLogs'
type CustomerHandlerService_ListAuditLogs_Call struct {
	*mock.Call
}

// ListAuditLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - page int
//   - pageSize int
func (_e *CustomerHandlerService_Expecter) ListAuditLogs(ctx interface{}, customerID interface{}, page interface{}, pageSize interface{}) *CustomerHandlerService_ListAuditLogs_Call {
	return &CustomerHandlerService_ListAuditLogs_Call{Call: _e.mock.On("ListAuditLogs", ctx, customerID, page, pageSize)}
}

func (_c *CustomerHandlerService_ListAuditLogs_Call) Run(run func(ctx context.Context, customerID string, page int, pageSize int)) *CustomerHandlerService_ListAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_ListAuditLogs_Call) Return(auditLogListResponse *model.AuditLogListResponse, err error) *CustomerHandlerService_ListAuditLogs_Call {
	_c.Call.Return(auditLogListResponse, err)
	return _c
}

func (_c *CustomerHandlerService_ListAuditLogs_Call) RunAndReturn(run func(ctx context.Context, customerID string, page int, pageSize int) (*model.AuditLogListResponse, error)) *CustomerHandlerService_ListAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompanyRoles provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) ListCompanyRoles(ctx context.Context, customerID string) (*model.CompanyRoleListResponse, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanyRoles")
	}

	var r0 *model.CompanyRoleListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CompanyRoleListResponse, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CompanyRoleListResponse); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CompanyRoleListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_ListCompanyRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanyRoles'
type CustomerHandlerService_ListCompanyRoles_Call struct {
	*mock.Call
}

// ListCompanyRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *CustomerHandlerService_Expecter) ListCompanyRoles(ctx interface{}, customerID interface{}) *CustomerHandlerService_ListCompanyRoles_Call {
	return &CustomerHandlerService_ListCompanyRoles_Call{Call: _e.mock.On("ListCompanyRoles", ctx, customerID)}
}

func (_c *CustomerHandlerService_ListCompanyRoles_Call) Run(run func(ctx context.Context, customerID string)) *CustomerHandlerService_ListCompanyRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_ListCompanyRoles_Call) Return(companyRoleListResponse *model.CompanyRoleListResponse, err error) *CustomerHandlerService_ListCompanyRoles_Call {
	_c.Call.Return(companyRoleListResponse, err)
	return _c
}

func (_c *CustomerHandlerService_ListCompanyRoles_Call) RunAndReturn(run func(ctx context.Context, customerID string) (*model.CompanyRoleListResponse, error)) *CustomerHandlerService_ListCompanyRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListCustomers provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) ListCustomers(ctx context.Context, status *string, page *int, pageSize *int) (*model.CustomerListResponse, error) {
	ret := _mock.Called(ctx, status, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListCustomers")
	}

	var r0 *model.CustomerListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *int, *int) (*model.CustomerListResponse, error)); ok {
		return returnFunc(ctx, status, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *int, *int) *model.CustomerListResponse); ok {
		r0 = returnFunc(ctx, status, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *int, *int) error); ok {
		r1 = returnFunc(ctx, status, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_ListCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCustomers'
type CustomerHandlerService_ListCustomers_Call struct {
	*mock.Call
}

// ListCustomers is a helper method to define mock.On call
//   - ctx context.Context
//   - status *string
//   - page *int
//   - pageSize *int
func (_e *CustomerHandlerService_Expecter) ListCustomers(ctx interface{}, status interface{}, page interface{}, pageSize interface{}) *CustomerHandlerService_ListCustomers_Call {
	return &CustomerHandlerService_ListCustomers_Call{Call: _e.mock.On("ListCustomers", ctx, status, page, pageSize)}
}

func (_c *CustomerHandlerService_ListCustomers_Call) Run(run func(ctx context.Context, status *string, page *int, pageSize *int)) *CustomerHandlerService_ListCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_ListCustomers_Call) Return(customerListResponse *model.CustomerListResponse, err error) *CustomerHandlerService_ListCustomers_Call {
	_c.Call.Return(customerListResponse, err)
	return _c
}

func (_c *CustomerHandlerService_ListCustomers_Call) RunAndReturn(run func(ctx context.Context, status *string, page *int, pageSize *int) (*model.CustomerListResponse, error)) *CustomerHandlerService_ListCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) RegisterCustomer(ctx context.Context, req *model.RegisterCustomerRequest) (*model.RegisterCustomerResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCustomer")
	}

	var r0 *model.RegisterCustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterCustomerRequest) (*model.RegisterCustomerResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.RegisterCustomerRequest) *model.RegisterCustomerResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RegisterCustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.RegisterCustomerRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_RegisterCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCustomer'
type CustomerHandlerService_RegisterCustomer_Call struct {
	*mock.Call
}

// RegisterCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.RegisterCustomerRequest
func (_e *CustomerHandlerService_Expecter) RegisterCustomer(ctx interface{}, req interface{}) *CustomerHandlerService_RegisterCustomer_Call {
	return &CustomerHandlerService_RegisterCustomer_Call{Call: _e.mock.On("RegisterCustomer", ctx, req)}
}

func (_c *CustomerHandlerService_RegisterCustomer_Call) Run(run func(ctx context.Context, req *model.RegisterCustomerRequest)) *CustomerHandlerService_RegisterCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.RegisterCustomerRequest
		if args[1] != nil {
			arg1 = args[1].(*model.RegisterCustomerRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_RegisterCustomer_Call) Return(registerCustomerResponse *model.RegisterCustomerResponse, err error) *CustomerHandlerService_RegisterCustomer_Call {
	_c.Call.Return(registerCustomerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_RegisterCustomer_Call) RunAndReturn(run func(ctx context.Context, req *model.RegisterCustomerRequest) (*model.RegisterCustomerResponse, error)) *CustomerHandlerService_RegisterCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// RejectCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) RejectCustomer(ctx context.Context, id string, reason string) error {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for RejectCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerHandlerService_RejectCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectCustomer'
type CustomerHandlerService_RejectCustomer_Call struct {
	*mock.Call
}

// RejectCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reason string
func (_e *CustomerHandlerService_Expecter) RejectCustomer(ctx interface{}, id interface{}, reason interface{}) *CustomerHandlerService_RejectCustomer_Call {
	return &CustomerHandlerService_RejectCustomer_Call{Call: _e.mock.On("RejectCustomer", ctx, id, reason)}
}

func (_c *CustomerHandlerService_RejectCustomer_Call) Run(run func(ctx context.Context, id string, reason string)) *CustomerHandlerService_RejectCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_RejectCustomer_Call) Return(err error) *CustomerHandlerService_RejectCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerHandlerService_RejectCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, reason string) error) *CustomerHandlerService_RejectCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) RestoreCustomer(ctx context.Context, id string, restoredBy string) (*model.CustomerResponse, error) {
	ret := _mock.Called(ctx, id, restoredBy)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCustomer")
	}

	var r0 *model.CustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.CustomerResponse, error)); ok {
		return returnFunc(ctx, id, restoredBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.CustomerResponse); ok {
		r0 = returnFunc(ctx, id, restoredBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, id, restoredBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_RestoreCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreCustomer'
type CustomerHandlerService_RestoreCustomer_Call struct {
	*mock.Call
}

// RestoreCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - restoredBy string
func (_e *CustomerHandlerService_Expecter) RestoreCustomer(ctx interface{}, id interface{}, restoredBy interface{}) *CustomerHandlerService_RestoreCustomer_Call {
	return &CustomerHandlerService_RestoreCustomer_Call{Call: _e.mock.On("RestoreCustomer", ctx, id, restoredBy)}
}

func (_c *CustomerHandlerService_RestoreCustomer_Call) Run(run func(ctx context.Context, id string, restoredBy string)) *CustomerHandlerService_RestoreCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_RestoreCustomer_Call) Return(customerResponse *model.CustomerResponse, err error) *CustomerHandlerService_RestoreCustomer_Call {
	_c.Call.Return(customerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_RestoreCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, restoredBy string) (*model.CustomerResponse, error)) *CustomerHandlerService_RestoreCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// SuspendCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) SuspendCustomer(ctx context.Context, id string, reason string) error {
	ret := _mock.Called(ctx, id, reason)

	if len(ret) == 0 {
		panic("no return value specified for SuspendCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerHandlerService_SuspendCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuspendCustomer'
type CustomerHandlerService_SuspendCustomer_Call struct {
	*mock.Call
}

// SuspendCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - reason string
func (_e *CustomerHandlerService_Expecter) SuspendCustomer(ctx interface{}, id interface{}, reason interface{}) *CustomerHandlerService_SuspendCustomer_Call {
	return &CustomerHandlerService_SuspendCustomer_Call{Call: _e.mock.On("SuspendCustomer", ctx, id, reason)}
}

func (_c *CustomerHandlerService_SuspendCustomer_Call) Run(run func(ctx context.Context, id string, reason string)) *CustomerHandlerService_SuspendCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_SuspendCustomer_Call) Return(err error) *CustomerHandlerService_SuspendCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerHandlerService_SuspendCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, reason string) error) *CustomerHandlerService_SuspendCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomer provides a mock function for the type CustomerHandlerService
func (_mock *CustomerHandlerService) UpdateCustomer(ctx context.Context, id string, req *model.UpdateCustomerRequest) (*model.CustomerResponse, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 *model.CustomerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateCustomerRequest) (*model.CustomerResponse, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateCustomerRequest) *model.CustomerResponse); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CustomerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.UpdateCustomerRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerHandlerService_UpdateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomer'
type CustomerHandlerService_UpdateCustomer_Call struct {
	*mock.Call
}

// UpdateCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *model.UpdateCustomerRequest
func (_e *CustomerHandlerService_Expecter) UpdateCustomer(ctx interface{}, id interface{}, req interface{}) *CustomerHandlerService_UpdateCustomer_Call {
	return &CustomerHandlerService_UpdateCustomer_Call{Call: _e.mock.On("UpdateCustomer", ctx, id, req)}
}

func (_c *CustomerHandlerService_UpdateCustomer_Call) Run(run func(ctx context.Context, id string, req *model.UpdateCustomerRequest)) *CustomerHandlerService_UpdateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.UpdateCustomerRequest
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateCustomerRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerHandlerService_UpdateCustomer_Call) Return(customerResponse *model.CustomerResponse, err error) *CustomerHandlerService_UpdateCustomer_Call {
	_c.Call.Return(customerResponse, err)
	return _c
}

func (_c *CustomerHandlerService_UpdateCustomer_Call) RunAndReturn(run func(ctx context.Context, id string, req *model.UpdateCustomerRequest) (*model.CustomerResponse, error)) *CustomerHandlerService_UpdateCustomer_Call {
	_c.Call.Return(run)
	return _c
}
