// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/beabys/wms/customer-service/internal/domain/customer/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

type AuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLogRepository) EXPECT() *AuditLogRepository_Expecter {
	return &AuditLogRepository_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function for the type AuditLogRepository
func (_mock *AuditLogRepository) Insert(ctx context.Context, log *model.AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditLogRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type AuditLogRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - log *model.AuditLog
func (_e *AuditLogRepository_Expecter) Insert(ctx interface{}, log interface{}) *AuditLogRepository_Insert_Call {
	return &AuditLogRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, log)}
}

func (_c *AuditLogRepository_Insert_Call) Run(run func(ctx context.Context, log *model.AuditLog)) *AuditLogRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*model.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditLogRepository_Insert_Call) Return(err error) *AuditLogRepository_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditLogRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, log *model.AuditLog) error) *AuditLogRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCustomerID provides a mock function for the type AuditLogRepository
func (_mock *AuditLogRepository) ListByCustomerID(ctx context.Context, customerID string, page int, pageSize int) ([]*model.AuditLog, int, error) {
	ret := _mock.Called(ctx, customerID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByCustomerID")
	}

	var r0 []*model.AuditLog
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.AuditLog, int, error)); ok {
		return returnFunc(ctx, customerID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.AuditLog); ok {
		r0 = returnFunc(ctx, customerID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = returnFunc(ctx, customerID, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, customerID, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuditLogRepository_ListByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCustomerID'
type AuditLogRepository_ListByCustomerID_Call struct {
	*mock.Call
}

// ListByCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - page int
//   - pageSize int
func (_e *AuditLogRepository_Expecter) ListByCustomerID(ctx interface{}, customerID interface{}, page interface{}, pageSize interface{}) *AuditLogRepository_ListByCustomerID_Call {
	return &AuditLogRepository_ListByCustomerID_Call{Call: _e.mock.On("ListByCustomerID", ctx, customerID, page, pageSize)}
}

func (_c *AuditLogRepository_ListByCustomerID_Call) Run(run func(ctx context.Context, customerID string, page int, pageSize int)) *AuditLogRepository_ListByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuditLogRepository_ListByCustomerID_Call) Return(auditLogs []*model.AuditLog, n int, err error) *AuditLogRepository_ListByCustomerID_Call {
	_c.Call.Return(auditLogs, n, err)
	return _c
}

func (_c *AuditLogRepository_ListByCustomerID_Call) RunAndReturn(run func(ctx context.Context, customerID string, page int, pageSize int) ([]*model.AuditLog, int, error)) *AuditLogRepository_ListByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}
