// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/beabys/wms/customer-service/internal/domain/customer/model"
	mock "github.com/stretchr/testify/mock"
)

// NewCompanyRepository creates a new instance of CompanyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyRepository {
	mock := &CompanyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompanyRepository is an autogenerated mock type for the CompanyRepository type
type CompanyRepository struct {
	mock.Mock
}

type CompanyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyRepository) EXPECT() *CompanyRepository_Expecter {
	return &CompanyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) Create(ctx context.Context, company *model.Company) error {
	ret := _mock.Called(ctx, company)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Company) error); ok {
		r0 = returnFunc(ctx, company)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CompanyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CompanyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - company *model.Company
func (_e *CompanyRepository_Expecter) Create(ctx interface{}, company interface{}) *CompanyRepository_Create_Call {
	return &CompanyRepository_Create_Call{Call: _e.mock.On("Create", ctx, company)}
}

func (_c *CompanyRepository_Create_Call) Run(run func(ctx context.Context, company *model.Company)) *CompanyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Company
		if args[1] != nil {
			arg1 = args[1].(*model.Company)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_Create_Call) Return(err error) *CompanyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CompanyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, company *model.Company) error) *CompanyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCustomerID provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) GetByCustomerID(ctx context.Context, customerID string) (*model.Company, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCustomerID")
	}

	var r0 *model.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Company, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Company); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_GetByCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCustomerID'
type CompanyRepository_GetByCustomerID_Call struct {
	*mock.Call
}

// GetByCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *CompanyRepository_Expecter) GetByCustomerID(ctx interface{}, customerID interface{}) *CompanyRepository_GetByCustomerID_Call {
	return &CompanyRepository_GetByCustomerID_Call{Call: _e.mock.On("GetByCustomerID", ctx, customerID)}
}

func (_c *CompanyRepository_GetByCustomerID_Call) Run(run func(ctx context.Context, customerID string)) *CompanyRepository_GetByCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_GetByCustomerID_Call) Return(company *model.Company, err error) *CompanyRepository_GetByCustomerID_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *CompanyRepository_GetByCustomerID_Call) RunAndReturn(run func(ctx context.Context, customerID string) (*model.Company, error)) *CompanyRepository_GetByCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type CompanyRepository
func (_mock *CompanyRepository) GetByID(ctx context.Context, id string) (*model.Company, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Company
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Company, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Company); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Company)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CompanyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CompanyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CompanyRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CompanyRepository_GetByID_Call {
	return &CompanyRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CompanyRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *CompanyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CompanyRepository_GetByID_Call) Return(company *model.Company, err error) *CompanyRepository_GetByID_Call {
	_c.Call.Return(company, err)
	return _c
}

func (_c *CompanyRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Company, error)) *CompanyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
