// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecase

import (
	"context"

	"github.com/beabys/wms/proto/gen/go/auth/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewGrpcClient creates a new instance of GrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GrpcClient {
	mock := &GrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GrpcClient is an autogenerated mock type for the GrpcClient type
type GrpcClient struct {
	mock.Mock
}

type GrpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *GrpcClient) EXPECT() *GrpcClient_Expecter {
	return &GrpcClient_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function for the type GrpcClient
func (_mock *GrpcClient) AssignRole(ctx context.Context, userID string, role string) (*authv1.AssignRoleResponse, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 *authv1.AssignRoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*authv1.AssignRoleResponse, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *authv1.AssignRoleResponse); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.AssignRoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type GrpcClient_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
func (_e *GrpcClient_Expecter) AssignRole(ctx interface{}, userID interface{}, role interface{}) *GrpcClient_AssignRole_Call {
	return &GrpcClient_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, role)}
}

func (_c *GrpcClient_AssignRole_Call) Run(run func(ctx context.Context, userID string, role string)) *GrpcClient_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_AssignRole_Call) Return(assignRoleResponse *authv1.AssignRoleResponse, err error) *GrpcClient_AssignRole_Call {
	_c.Call.Return(assignRoleResponse, err)
	return _c
}

func (_c *GrpcClient_AssignRole_Call) RunAndReturn(run func(ctx context.Context, userID string, role string) (*authv1.AssignRoleResponse, error)) *GrpcClient_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// CancelInvite provides a mock function for the type GrpcClient
func (_mock *GrpcClient) CancelInvite(ctx context.Context, token string) (*authv1.CancelInviteResponse, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvite")
	}

	var r0 *authv1.CancelInviteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.CancelInviteResponse, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.CancelInviteResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.CancelInviteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_CancelInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvite'
type GrpcClient_CancelInvite_Call struct {
	*mock.Call
}

// CancelInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *GrpcClient_Expecter) CancelInvite(ctx interface{}, token interface{}) *GrpcClient_CancelInvite_Call {
	return &GrpcClient_CancelInvite_Call{Call: _e.mock.On("CancelInvite", ctx, token)}
}

func (_c *GrpcClient_CancelInvite_Call) Run(run func(ctx context.Context, token string)) *GrpcClient_CancelInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_CancelInvite_Call) Return(cancelInviteResponse *authv1.CancelInviteResponse, err error) *GrpcClient_CancelInvite_Call {
	_c.Call.Return(cancelInviteResponse, err)
	return _c
}

func (_c *GrpcClient_CancelInvite_Call) RunAndReturn(run func(ctx context.Context, token string) (*authv1.CancelInviteResponse, error)) *GrpcClient_CancelInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type GrpcClient
func (_mock *GrpcClient) CreateRole(ctx context.Context, req *authv1.CreateRoleRequest) (*authv1.CreateRoleResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *authv1.CreateRoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.CreateRoleRequest) (*authv1.CreateRoleResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.CreateRoleRequest) *authv1.CreateRoleResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.CreateRoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.CreateRoleRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type GrpcClient_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.CreateRoleRequest
func (_e *GrpcClient_Expecter) CreateRole(ctx interface{}, req interface{}) *GrpcClient_CreateRole_Call {
	return &GrpcClient_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, req)}
}

func (_c *GrpcClient_CreateRole_Call) Run(run func(ctx context.Context, req *authv1.CreateRoleRequest)) *GrpcClient_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.CreateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.CreateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_CreateRole_Call) Return(createRoleResponse *authv1.CreateRoleResponse, err error) *GrpcClient_CreateRole_Call {
	_c.Call.Return(createRoleResponse, err)
	return _c
}

func (_c *GrpcClient_CreateRole_Call) RunAndReturn(run func(ctx context.Context, req *authv1.CreateRoleRequest) (*authv1.CreateRoleResponse, error)) *GrpcClient_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type GrpcClient
func (_mock *GrpcClient) CreateUser(ctx context.Context, req *authv1.CreateUserRequest) (*authv1.CreateUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *authv1.CreateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.CreateUserRequest) (*authv1.CreateUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.CreateUserRequest) *authv1.CreateUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.CreateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.CreateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type GrpcClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.CreateUserRequest
func (_e *GrpcClient_Expecter) CreateUser(ctx interface{}, req interface{}) *GrpcClient_CreateUser_Call {
	return &GrpcClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, req)}
}

func (_c *GrpcClient_CreateUser_Call) Run(run func(ctx context.Context, req *authv1.CreateUserRequest)) *GrpcClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_CreateUser_Call) Return(createUserResponse *authv1.CreateUserResponse, err error) *GrpcClient_CreateUser_Call {
	_c.Call.Return(createUserResponse, err)
	return _c
}

func (_c *GrpcClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, req *authv1.CreateUserRequest) (*authv1.CreateUserResponse, error)) *GrpcClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type GrpcClient
func (_mock *GrpcClient) DeleteUser(ctx context.Context, id string) (*authv1.DeleteUserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *authv1.DeleteUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.DeleteUserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.DeleteUserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.DeleteUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type GrpcClient_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GrpcClient_Expecter) DeleteUser(ctx interface{}, id interface{}) *GrpcClient_DeleteUser_Call {
	return &GrpcClient_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *GrpcClient_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *GrpcClient_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_DeleteUser_Call) Return(deleteUserResponse *authv1.DeleteUserResponse, err error) *GrpcClient_DeleteUser_Call {
	_c.Call.Return(deleteUserResponse, err)
	return _c
}

func (_c *GrpcClient_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id string) (*authv1.DeleteUserResponse, error)) *GrpcClient_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type GrpcClient
func (_mock *GrpcClient) GetUser(ctx context.Context, id string) (*authv1.GetUserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *authv1.GetUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.GetUserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.GetUserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.GetUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type GrpcClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GrpcClient_Expecter) GetUser(ctx interface{}, id interface{}) *GrpcClient_GetUser_Call {
	return &GrpcClient_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *GrpcClient_GetUser_Call) Run(run func(ctx context.Context, id string)) *GrpcClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_GetUser_Call) Return(getUserResponse *authv1.GetUserResponse, err error) *GrpcClient_GetUser_Call {
	_c.Call.Return(getUserResponse, err)
	return _c
}

func (_c *GrpcClient_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (*authv1.GetUserResponse, error)) *GrpcClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUser provides a mock function for the type GrpcClient
func (_mock *GrpcClient) InviteUser(ctx context.Context, email string, invitedBy string) (*authv1.InviteUserResponse, error) {
	ret := _mock.Called(ctx, email, invitedBy)

	if len(ret) == 0 {
		panic("no return value specified for InviteUser")
	}

	var r0 *authv1.InviteUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*authv1.InviteUserResponse, error)); ok {
		return returnFunc(ctx, email, invitedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *authv1.InviteUserResponse); ok {
		r0 = returnFunc(ctx, email, invitedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.InviteUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, invitedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_InviteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUser'
type GrpcClient_InviteUser_Call struct {
	*mock.Call
}

// InviteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - invitedBy string
func (_e *GrpcClient_Expecter) InviteUser(ctx interface{}, email interface{}, invitedBy interface{}) *GrpcClient_InviteUser_Call {
	return &GrpcClient_InviteUser_Call{Call: _e.mock.On("InviteUser", ctx, email, invitedBy)}
}

func (_c *GrpcClient_InviteUser_Call) Run(run func(ctx context.Context, email string, invitedBy string)) *GrpcClient_InviteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_InviteUser_Call) Return(inviteUserResponse *authv1.InviteUserResponse, err error) *GrpcClient_InviteUser_Call {
	_c.Call.Return(inviteUserResponse, err)
	return _c
}

func (_c *GrpcClient_InviteUser_Call) RunAndReturn(run func(ctx context.Context, email string, invitedBy string) (*authv1.InviteUserResponse, error)) *GrpcClient_InviteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvites provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListInvites(ctx context.Context, req *authv1.ListInvitesRequest) (*authv1.ListInvitesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListInvites")
	}

	var r0 *authv1.ListInvitesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListInvitesRequest) (*authv1.ListInvitesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListInvitesRequest) *authv1.ListInvitesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ListInvitesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.ListInvitesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvites'
type GrpcClient_ListInvites_Call struct {
	*mock.Call
}

// ListInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.ListInvitesRequest
func (_e *GrpcClient_Expecter) ListInvites(ctx interface{}, req interface{}) *GrpcClient_ListInvites_Call {
	return &GrpcClient_ListInvites_Call{Call: _e.mock.On("ListInvites", ctx, req)}
}

func (_c *GrpcClient_ListInvites_Call) Run(run func(ctx context.Context, req *authv1.ListInvitesRequest)) *GrpcClient_ListInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.ListInvitesRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.ListInvitesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListInvites_Call) Return(listInvitesResponse *authv1.ListInvitesResponse, err error) *GrpcClient_ListInvites_Call {
	_c.Call.Return(listInvitesResponse, err)
	return _c
}

func (_c *GrpcClient_ListInvites_Call) RunAndReturn(run func(ctx context.Context, req *authv1.ListInvitesRequest) (*authv1.ListInvitesResponse, error)) *GrpcClient_ListInvites_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListRoles(ctx context.Context, req *authv1.ListRolesRequest) (*authv1.ListRolesResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 *authv1.ListRolesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListRolesRequest) (*authv1.ListRolesResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListRolesRequest) *authv1.ListRolesResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ListRolesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.ListRolesRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type GrpcClient_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.ListRolesRequest
func (_e *GrpcClient_Expecter) ListRoles(ctx interface{}, req interface{}) *GrpcClient_ListRoles_Call {
	return &GrpcClient_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx, req)}
}

func (_c *GrpcClient_ListRoles_Call) Run(run func(ctx context.Context, req *authv1.ListRolesRequest)) *GrpcClient_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.ListRolesRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.ListRolesRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListRoles_Call) Return(listRolesResponse *authv1.ListRolesResponse, err error) *GrpcClient_ListRoles_Call {
	_c.Call.Return(listRolesResponse, err)
	return _c
}

func (_c *GrpcClient_ListRoles_Call) RunAndReturn(run func(ctx context.Context, req *authv1.ListRolesRequest) (*authv1.ListRolesResponse, error)) *GrpcClient_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ListUsers(ctx context.Context, req *authv1.ListUsersRequest) (*authv1.ListUsersResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *authv1.ListUsersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListUsersRequest) (*authv1.ListUsersResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.ListUsersRequest) *authv1.ListUsersResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ListUsersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.ListUsersRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type GrpcClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.ListUsersRequest
func (_e *GrpcClient_Expecter) ListUsers(ctx interface{}, req interface{}) *GrpcClient_ListUsers_Call {
	return &GrpcClient_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, req)}
}

func (_c *GrpcClient_ListUsers_Call) Run(run func(ctx context.Context, req *authv1.ListUsersRequest)) *GrpcClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.ListUsersRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.ListUsersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ListUsers_Call) Return(listUsersResponse *authv1.ListUsersResponse, err error) *GrpcClient_ListUsers_Call {
	_c.Call.Return(listUsersResponse, err)
	return _c
}

func (_c *GrpcClient_ListUsers_Call) RunAndReturn(run func(ctx context.Context, req *authv1.ListUsersRequest) (*authv1.ListUsersResponse, error)) *GrpcClient_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type GrpcClient
func (_mock *GrpcClient) Login(ctx context.Context, email string, password string) (*authv1.LoginResponse, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *authv1.LoginResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*authv1.LoginResponse, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *authv1.LoginResponse); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LoginResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type GrpcClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *GrpcClient_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *GrpcClient_Login_Call {
	return &GrpcClient_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *GrpcClient_Login_Call) Run(run func(ctx context.Context, email string, password string)) *GrpcClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GrpcClient_Login_Call) Return(loginResponse *authv1.LoginResponse, err error) *GrpcClient_Login_Call {
	_c.Call.Return(loginResponse, err)
	return _c
}

func (_c *GrpcClient_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*authv1.LoginResponse, error)) *GrpcClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type GrpcClient
func (_mock *GrpcClient) Logout(ctx context.Context, refreshToken string) (*authv1.LogoutResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 *authv1.LogoutResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.LogoutResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.LogoutResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.LogoutResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type GrpcClient_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *GrpcClient_Expecter) Logout(ctx interface{}, refreshToken interface{}) *GrpcClient_Logout_Call {
	return &GrpcClient_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *GrpcClient_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *GrpcClient_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_Logout_Call) Return(logoutResponse *authv1.LogoutResponse, err error) *GrpcClient_Logout_Call {
	_c.Call.Return(logoutResponse, err)
	return _c
}

func (_c *GrpcClient_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*authv1.LogoutResponse, error)) *GrpcClient_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type GrpcClient
func (_mock *GrpcClient) RefreshToken(ctx context.Context, refreshToken string) (*authv1.RefreshTokenResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *authv1.RefreshTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.RefreshTokenResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.RefreshTokenResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.RefreshTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type GrpcClient_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *GrpcClient_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *GrpcClient_RefreshToken_Call {
	return &GrpcClient_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *GrpcClient_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *GrpcClient_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_RefreshToken_Call) Return(refreshTokenResponse *authv1.RefreshTokenResponse, err error) *GrpcClient_RefreshToken_Call {
	_c.Call.Return(refreshTokenResponse, err)
	return _c
}

func (_c *GrpcClient_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*authv1.RefreshTokenResponse, error)) *GrpcClient_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type GrpcClient
func (_mock *GrpcClient) UpdateUser(ctx context.Context, req *authv1.UpdateUserRequest) (*authv1.UpdateUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *authv1.UpdateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.UpdateUserRequest) (*authv1.UpdateUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *authv1.UpdateUserRequest) *authv1.UpdateUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.UpdateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *authv1.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type GrpcClient_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *authv1.UpdateUserRequest
func (_e *GrpcClient_Expecter) UpdateUser(ctx interface{}, req interface{}) *GrpcClient_UpdateUser_Call {
	return &GrpcClient_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, req)}
}

func (_c *GrpcClient_UpdateUser_Call) Run(run func(ctx context.Context, req *authv1.UpdateUserRequest)) *GrpcClient_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *authv1.UpdateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*authv1.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_UpdateUser_Call) Return(updateUserResponse *authv1.UpdateUserResponse, err error) *GrpcClient_UpdateUser_Call {
	_c.Call.Return(updateUserResponse, err)
	return _c
}

func (_c *GrpcClient_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, req *authv1.UpdateUserRequest) (*authv1.UpdateUserResponse, error)) *GrpcClient_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type GrpcClient
func (_mock *GrpcClient) ValidateToken(ctx context.Context, token string) (*authv1.ValidateTokenResponse, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *authv1.ValidateTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*authv1.ValidateTokenResponse, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *authv1.ValidateTokenResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*authv1.ValidateTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GrpcClient_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type GrpcClient_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *GrpcClient_Expecter) ValidateToken(ctx interface{}, token interface{}) *GrpcClient_ValidateToken_Call {
	return &GrpcClient_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *GrpcClient_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *GrpcClient_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GrpcClient_ValidateToken_Call) Return(validateTokenResponse *authv1.ValidateTokenResponse, err error) *GrpcClient_ValidateToken_Call {
	_c.Call.Return(validateTokenResponse, err)
	return _c
}

func (_c *GrpcClient_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*authv1.ValidateTokenResponse, error)) *GrpcClient_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
