// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package httpadapter

import (
	"context"

	"github.com/beabys/wms/auth-service-bff/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthHandlerService creates a new instance of AuthHandlerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthHandlerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthHandlerService {
	mock := &AuthHandlerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthHandlerService is an autogenerated mock type for the AuthHandlerService type
type AuthHandlerService struct {
	mock.Mock
}

type AuthHandlerService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthHandlerService) EXPECT() *AuthHandlerService_Expecter {
	return &AuthHandlerService_Expecter{mock: &_m.Mock}
}

// AssignRole provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) AssignRole(ctx context.Context, userID string, role string) error {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AssignRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHandlerService_AssignRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignRole'
type AuthHandlerService_AssignRole_Call struct {
	*mock.Call
}

// AssignRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
func (_e *AuthHandlerService_Expecter) AssignRole(ctx interface{}, userID interface{}, role interface{}) *AuthHandlerService_AssignRole_Call {
	return &AuthHandlerService_AssignRole_Call{Call: _e.mock.On("AssignRole", ctx, userID, role)}
}

func (_c *AuthHandlerService_AssignRole_Call) Run(run func(ctx context.Context, userID string, role string)) *AuthHandlerService_AssignRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthHandlerService_AssignRole_Call) Return(err error) *AuthHandlerService_AssignRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHandlerService_AssignRole_Call) RunAndReturn(run func(ctx context.Context, userID string, role string) error) *AuthHandlerService_AssignRole_Call {
	_c.Call.Return(run)
	return _c
}

// CancelInvite provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) CancelInvite(ctx context.Context, token string) (*model.CancelInviteResponse, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvite")
	}

	var r0 *model.CancelInviteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.CancelInviteResponse, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.CancelInviteResponse); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CancelInviteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_CancelInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvite'
type AuthHandlerService_CancelInvite_Call struct {
	*mock.Call
}

// CancelInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthHandlerService_Expecter) CancelInvite(ctx interface{}, token interface{}) *AuthHandlerService_CancelInvite_Call {
	return &AuthHandlerService_CancelInvite_Call{Call: _e.mock.On("CancelInvite", ctx, token)}
}

func (_c *AuthHandlerService_CancelInvite_Call) Run(run func(ctx context.Context, token string)) *AuthHandlerService_CancelInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_CancelInvite_Call) Return(cancelInviteResponse *model.CancelInviteResponse, err error) *AuthHandlerService_CancelInvite_Call {
	_c.Call.Return(cancelInviteResponse, err)
	return _c
}

func (_c *AuthHandlerService_CancelInvite_Call) RunAndReturn(run func(ctx context.Context, token string) (*model.CancelInviteResponse, error)) *AuthHandlerService_CancelInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRole provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) CreateRole(ctx context.Context, req *model.CreateRoleRequest) (*model.RoleResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 *model.RoleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) (*model.RoleResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateRoleRequest) *model.RoleResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CreateRoleRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_CreateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRole'
type AuthHandlerService_CreateRole_Call struct {
	*mock.Call
}

// CreateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateRoleRequest
func (_e *AuthHandlerService_Expecter) CreateRole(ctx interface{}, req interface{}) *AuthHandlerService_CreateRole_Call {
	return &AuthHandlerService_CreateRole_Call{Call: _e.mock.On("CreateRole", ctx, req)}
}

func (_c *AuthHandlerService_CreateRole_Call) Run(run func(ctx context.Context, req *model.CreateRoleRequest)) *AuthHandlerService_CreateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CreateRoleRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CreateRoleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_CreateRole_Call) Return(roleResponse *model.RoleResponse, err error) *AuthHandlerService_CreateRole_Call {
	_c.Call.Return(roleResponse, err)
	return _c
}

func (_c *AuthHandlerService_CreateRole_Call) RunAndReturn(run func(ctx context.Context, req *model.CreateRoleRequest) (*model.RoleResponse, error)) *AuthHandlerService_CreateRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) CreateUser(ctx context.Context, req *model.CreateUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.CreateUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.CreateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AuthHandlerService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req *model.CreateUserRequest
func (_e *AuthHandlerService_Expecter) CreateUser(ctx interface{}, req interface{}) *AuthHandlerService_CreateUser_Call {
	return &AuthHandlerService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, req)}
}

func (_c *AuthHandlerService_CreateUser_Call) Run(run func(ctx context.Context, req *model.CreateUserRequest)) *AuthHandlerService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(*model.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_CreateUser_Call) Return(userResponse *model.UserResponse, err error) *AuthHandlerService_CreateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *AuthHandlerService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, req *model.CreateUserRequest) (*model.UserResponse, error)) *AuthHandlerService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) DeleteUser(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHandlerService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type AuthHandlerService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthHandlerService_Expecter) DeleteUser(ctx interface{}, id interface{}) *AuthHandlerService_DeleteUser_Call {
	return &AuthHandlerService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *AuthHandlerService_DeleteUser_Call) Run(run func(ctx context.Context, id string)) *AuthHandlerService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_DeleteUser_Call) Return(err error) *AuthHandlerService_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHandlerService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id string) error) *AuthHandlerService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetMe provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) GetMe(ctx context.Context) (*model.UserResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.UserResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.UserResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type AuthHandlerService_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthHandlerService_Expecter) GetMe(ctx interface{}) *AuthHandlerService_GetMe_Call {
	return &AuthHandlerService_GetMe_Call{Call: _e.mock.On("GetMe", ctx)}
}

func (_c *AuthHandlerService_GetMe_Call) Run(run func(ctx context.Context)) *AuthHandlerService_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHandlerService_GetMe_Call) Return(userResponse *model.UserResponse, err error) *AuthHandlerService_GetMe_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *AuthHandlerService_GetMe_Call) RunAndReturn(run func(ctx context.Context) (*model.UserResponse, error)) *AuthHandlerService_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) GetUser(ctx context.Context, id string) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type AuthHandlerService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *AuthHandlerService_Expecter) GetUser(ctx interface{}, id interface{}) *AuthHandlerService_GetUser_Call {
	return &AuthHandlerService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, id)}
}

func (_c *AuthHandlerService_GetUser_Call) Run(run func(ctx context.Context, id string)) *AuthHandlerService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_GetUser_Call) Return(userResponse *model.UserResponse, err error) *AuthHandlerService_GetUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *AuthHandlerService_GetUser_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.UserResponse, error)) *AuthHandlerService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUser provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) InviteUser(ctx context.Context, email string, invitedBy string) (*model.InviteUserResponse, error) {
	ret := _mock.Called(ctx, email, invitedBy)

	if len(ret) == 0 {
		panic("no return value specified for InviteUser")
	}

	var r0 *model.InviteUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.InviteUserResponse, error)); ok {
		return returnFunc(ctx, email, invitedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.InviteUserResponse); ok {
		r0 = returnFunc(ctx, email, invitedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InviteUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, invitedBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_InviteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUser'
type AuthHandlerService_InviteUser_Call struct {
	*mock.Call
}

// InviteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - invitedBy string
func (_e *AuthHandlerService_Expecter) InviteUser(ctx interface{}, email interface{}, invitedBy interface{}) *AuthHandlerService_InviteUser_Call {
	return &AuthHandlerService_InviteUser_Call{Call: _e.mock.On("InviteUser", ctx, email, invitedBy)}
}

func (_c *AuthHandlerService_InviteUser_Call) Run(run func(ctx context.Context, email string, invitedBy string)) *AuthHandlerService_InviteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthHandlerService_InviteUser_Call) Return(inviteUserResponse *model.InviteUserResponse, err error) *AuthHandlerService_InviteUser_Call {
	_c.Call.Return(inviteUserResponse, err)
	return _c
}

func (_c *AuthHandlerService_InviteUser_Call) RunAndReturn(run func(ctx context.Context, email string, invitedBy string) (*model.InviteUserResponse, error)) *AuthHandlerService_InviteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListInvites provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) ListInvites(ctx context.Context, status *string, expired *bool, createdAfter *int64, createdBefore *int64, page *int, pageSize *int) (*model.InviteListResponse, error) {
	ret := _mock.Called(ctx, status, expired, createdAfter, createdBefore, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListInvites")
	}

	var r0 *model.InviteListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *bool, *int64, *int64, *int, *int) (*model.InviteListResponse, error)); ok {
		return returnFunc(ctx, status, expired, createdAfter, createdBefore, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *bool, *int64, *int64, *int, *int) *model.InviteListResponse); ok {
		r0 = returnFunc(ctx, status, expired, createdAfter, createdBefore, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.InviteListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *bool, *int64, *int64, *int, *int) error); ok {
		r1 = returnFunc(ctx, status, expired, createdAfter, createdBefore, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_ListInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListInvites'
type AuthHandlerService_ListInvites_Call struct {
	*mock.Call
}

// ListInvites is a helper method to define mock.On call
//   - ctx context.Context
//   - status *string
//   - expired *bool
//   - createdAfter *int64
//   - createdBefore *int64
//   - page *int
//   - pageSize *int
func (_e *AuthHandlerService_Expecter) ListInvites(ctx interface{}, status interface{}, expired interface{}, createdAfter interface{}, createdBefore interface{}, page interface{}, pageSize interface{}) *AuthHandlerService_ListInvites_Call {
	return &AuthHandlerService_ListInvites_Call{Call: _e.mock.On("ListInvites", ctx, status, expired, createdAfter, createdBefore, page, pageSize)}
}

func (_c *AuthHandlerService_ListInvites_Call) Run(run func(ctx context.Context, status *string, expired *bool, createdAfter *int64, createdBefore *int64, page *int, pageSize *int)) *AuthHandlerService_ListInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *bool
		if args[2] != nil {
			arg2 = args[2].(*bool)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		var arg5 *int
		if args[5] != nil {
			arg5 = args[5].(*int)
		}
		var arg6 *int
		if args[6] != nil {
			arg6 = args[6].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *AuthHandlerService_ListInvites_Call) Return(inviteListResponse *model.InviteListResponse, err error) *AuthHandlerService_ListInvites_Call {
	_c.Call.Return(inviteListResponse, err)
	return _c
}

func (_c *AuthHandlerService_ListInvites_Call) RunAndReturn(run func(ctx context.Context, status *string, expired *bool, createdAfter *int64, createdBefore *int64, page *int, pageSize *int) (*model.InviteListResponse, error)) *AuthHandlerService_ListInvites_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoles provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) ListRoles(ctx context.Context) (*model.RoleListResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoles")
	}

	var r0 *model.RoleListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.RoleListResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.RoleListResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.RoleListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_ListRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoles'
type AuthHandlerService_ListRoles_Call struct {
	*mock.Call
}

// ListRoles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AuthHandlerService_Expecter) ListRoles(ctx interface{}) *AuthHandlerService_ListRoles_Call {
	return &AuthHandlerService_ListRoles_Call{Call: _e.mock.On("ListRoles", ctx)}
}

func (_c *AuthHandlerService_ListRoles_Call) Run(run func(ctx context.Context)) *AuthHandlerService_ListRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuthHandlerService_ListRoles_Call) Return(roleListResponse *model.RoleListResponse, err error) *AuthHandlerService_ListRoles_Call {
	_c.Call.Return(roleListResponse, err)
	return _c
}

func (_c *AuthHandlerService_ListRoles_Call) RunAndReturn(run func(ctx context.Context) (*model.RoleListResponse, error)) *AuthHandlerService_ListRoles_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) ListUsers(ctx context.Context, role *string, customerID *string, page *int, pageSize *int) (*model.UserListResponse, error) {
	ret := _mock.Called(ctx, role, customerID, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *model.UserListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string, *int, *int) (*model.UserListResponse, error)); ok {
		return returnFunc(ctx, role, customerID, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *string, *int, *int) *model.UserListResponse); ok {
		r0 = returnFunc(ctx, role, customerID, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *string, *int, *int) error); ok {
		r1 = returnFunc(ctx, role, customerID, page, pageSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type AuthHandlerService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - role *string
//   - customerID *string
//   - page *int
//   - pageSize *int
func (_e *AuthHandlerService_Expecter) ListUsers(ctx interface{}, role interface{}, customerID interface{}, page interface{}, pageSize interface{}) *AuthHandlerService_ListUsers_Call {
	return &AuthHandlerService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, role, customerID, page, pageSize)}
}

func (_c *AuthHandlerService_ListUsers_Call) Run(run func(ctx context.Context, role *string, customerID *string, page *int, pageSize *int)) *AuthHandlerService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuthHandlerService_ListUsers_Call) Return(userListResponse *model.UserListResponse, err error) *AuthHandlerService_ListUsers_Call {
	_c.Call.Return(userListResponse, err)
	return _c
}

func (_c *AuthHandlerService_ListUsers_Call) RunAndReturn(run func(ctx context.Context, role *string, customerID *string, page *int, pageSize *int) (*model.UserListResponse, error)) *AuthHandlerService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) Login(ctx context.Context, email string, password string) (*model.AuthResponse, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*model.AuthResponse, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *model.AuthResponse); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthHandlerService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthHandlerService_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *AuthHandlerService_Login_Call {
	return &AuthHandlerService_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *AuthHandlerService_Login_Call) Run(run func(ctx context.Context, email string, password string)) *AuthHandlerService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthHandlerService_Login_Call) Return(authResponse *model.AuthResponse, err error) *AuthHandlerService_Login_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *AuthHandlerService_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*model.AuthResponse, error)) *AuthHandlerService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthHandlerService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthHandlerService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthHandlerService_Expecter) Logout(ctx interface{}, refreshToken interface{}) *AuthHandlerService_Logout_Call {
	return &AuthHandlerService_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *AuthHandlerService_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthHandlerService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_Logout_Call) Return(err error) *AuthHandlerService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthHandlerService_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *AuthHandlerService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *model.AuthResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.AuthResponse, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.AuthResponse); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type AuthHandlerService_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *AuthHandlerService_Expecter) RefreshToken(ctx interface{}, refreshToken interface{}) *AuthHandlerService_RefreshToken_Call {
	return &AuthHandlerService_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, refreshToken)}
}

func (_c *AuthHandlerService_RefreshToken_Call) Run(run func(ctx context.Context, refreshToken string)) *AuthHandlerService_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthHandlerService_RefreshToken_Call) Return(authResponse *model.AuthResponse, err error) *AuthHandlerService_RefreshToken_Call {
	_c.Call.Return(authResponse, err)
	return _c
}

func (_c *AuthHandlerService_RefreshToken_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*model.AuthResponse, error)) *AuthHandlerService_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type AuthHandlerService
func (_mock *AuthHandlerService) UpdateUser(ctx context.Context, id string, req *model.UpdateUserRequest) (*model.UserResponse, error) {
	ret := _mock.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *model.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateUserRequest) (*model.UserResponse, error)); ok {
		return returnFunc(ctx, id, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.UpdateUserRequest) *model.UserResponse); ok {
		r0 = returnFunc(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.UpdateUserRequest) error); ok {
		r1 = returnFunc(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthHandlerService_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type AuthHandlerService_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - req *model.UpdateUserRequest
func (_e *AuthHandlerService_Expecter) UpdateUser(ctx interface{}, id interface{}, req interface{}) *AuthHandlerService_UpdateUser_Call {
	return &AuthHandlerService_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, id, req)}
}

func (_c *AuthHandlerService_UpdateUser_Call) Run(run func(ctx context.Context, id string, req *model.UpdateUserRequest)) *AuthHandlerService_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.UpdateUserRequest
		if args[2] != nil {
			arg2 = args[2].(*model.UpdateUserRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthHandlerService_UpdateUser_Call) Return(userResponse *model.UserResponse, err error) *AuthHandlerService_UpdateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *AuthHandlerService_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, id string, req *model.UpdateUserRequest) (*model.UserResponse, error)) *AuthHandlerService_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
