// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/beabys/wms/customer-service/internal/application/customer/command"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthClient creates a new instance of AuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthClient {
	mock := &AuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthClient is an autogenerated mock type for the AuthClient type
type AuthClient struct {
	mock.Mock
}

type AuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthClient) EXPECT() *AuthClient_Expecter {
	return &AuthClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type AuthClient
func (_mock *AuthClient) CreateUser(ctx context.Context, req command.CreateUserRequest) (*command.CreateUserResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *command.CreateUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.CreateUserRequest) (*command.CreateUserResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.CreateUserRequest) *command.CreateUserResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.CreateUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, command.CreateUserRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AuthClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - req command.CreateUserRequest
func (_e *AuthClient_Expecter) CreateUser(ctx interface{}, req interface{}) *AuthClient_CreateUser_Call {
	return &AuthClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, req)}
}

func (_c *AuthClient_CreateUser_Call) Run(run func(ctx context.Context, req command.CreateUserRequest)) *AuthClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(command.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthClient_CreateUser_Call) Return(createUserResponse *command.CreateUserResponse, err error) *AuthClient_CreateUser_Call {
	_c.Call.Return(createUserResponse, err)
	return _c
}

func (_c *AuthClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, req command.CreateUserRequest) (*command.CreateUserResponse, error)) *AuthClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateInvite provides a mock function for the type AuthClient
func (_mock *AuthClient) ValidateInvite(ctx context.Context, token string) (string, string, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateInvite")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, token)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuthClient_ValidateInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateInvite'
type AuthClient_ValidateInvite_Call struct {
	*mock.Call
}

// ValidateInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthClient_Expecter) ValidateInvite(ctx interface{}, token interface{}) *AuthClient_ValidateInvite_Call {
	return &AuthClient_ValidateInvite_Call{Call: _e.mock.On("ValidateInvite", ctx, token)}
}

func (_c *AuthClient_ValidateInvite_Call) Run(run func(ctx context.Context, token string)) *AuthClient_ValidateInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthClient_ValidateInvite_Call) Return(email string, invitedBy string, err error) *AuthClient_ValidateInvite_Call {
	_c.Call.Return(email, invitedBy, err)
	return _c
}

func (_c *AuthClient_ValidateInvite_Call) RunAndReturn(run func(ctx context.Context, token string) (string, string, error)) *AuthClient_ValidateInvite_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type AuthClient
func (_mock *AuthClient) ValidateToken(ctx context.Context, token string) (*command.ValidateTokenResult, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *command.ValidateTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*command.ValidateTokenResult, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *command.ValidateTokenResult); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*command.ValidateTokenResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthClient_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type AuthClient_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *AuthClient_Expecter) ValidateToken(ctx interface{}, token interface{}) *AuthClient_ValidateToken_Call {
	return &AuthClient_ValidateToken_Call{Call: _e.mock.On("ValidateToken", ctx, token)}
}

func (_c *AuthClient_ValidateToken_Call) Run(run func(ctx context.Context, token string)) *AuthClient_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthClient_ValidateToken_Call) Return(validateTokenResult *command.ValidateTokenResult, err error) *AuthClient_ValidateToken_Call {
	_c.Call.Return(validateTokenResult, err)
	return _c
}

func (_c *AuthClient_ValidateToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*command.ValidateTokenResult, error)) *AuthClient_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
